### ISSUE TITLE
Remove SearchView start margin

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#101]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Remove `SearchView` start margin.
- Fix hint start position.

<img src=https://user-images.githubusercontent.com/6636072/72198706-a823f180-3474-11ea-9dfb-4a44406acb7e.png  width=50%>

 ## Links	

-

**Comment by Luecy1** [comment]
🙋

**Comment by roana0229** [comment]
@Luecy1 Thanks! assigned.

**Comment by Luecy1** [comment]
I am struggling now.:cold_sweat:

I thought that SearchView's  mergin adjust in layout.xml.
However, it put in menu.xml.
I will adjust margins in code.🤔

Would you please give me advice?:bow:

**Comment by roana0229** [comment]
> I will adjust margins in code.🤔

I think so too. But I don't know the solution too. 🤔 

layout is like this
<img src=https://user-images.githubusercontent.com/6636072/72525522-b2485480-38a7-11ea-8851-b3ab0462e294.png  width=50%>

I will try to remove square.

**Comment by roana0229** [comment]
Or `SearchView` does not have to be `menu`, so you can implement it like as `Toolbar`. 😄

**Comment by Luecy1** [comment]
Thank you for comments.
i keep trying.

**Comment by Luecy1** [comment]
I have a question.
How to implement MainActivity call SearchSessionsFragment method in DroidKaigi 2020 's architecture?
I want to transmission from SearchView's onQueryTextChange to searchSessionsViewModel.updateSearchQuery.

**Comment by Luecy1** [comment]
Please, unassigned me
https://github.com/DroidKaigi/conference-app-2020/pull/430#issuecomment-583717071

**Comment by takahirom** [comment]
It's ok. I think it is very difficult 👍
