### ISSUE TITLE
Navigation bar color disappears when switching DarkTheme

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2020#103]
**Overview (Required)**
- Happen on the session detail screen.  

**Steps To Reproduce**

**Expected behavior**
Same color as BottomAppBar.  

**Screenshots**

<img src="https://user-images.githubusercontent.com/13705006/72199263-eae9c780-347c-11ea-898a-b6c0f4a50d32.png" width="300px">

**Env:**
 - Device: Pixel3 XL
 - OS: 10.0
 - App Version or the branch master 

**Additional context**

**Comment by souta0104** [comment]
🙋‍♂️🙋‍♂️

**Comment by FujiKinaga** [comment]
@souta0104
Thanks. Assigned ! 👍

**Comment by souta0104** [comment]
I could not reproduce this bug.
I guess it is probably fixed in the latest version.

**Comment by FujiKinaga** [comment]
@souta0104 
Thanks for your response.
As you say, I also confirmed to be fixed in latest build.
I'll close this issue...😭 
If you have time, would you please try the next issue!
