### ISSUE TITLE
When BottomSheet is expanded, top left corner is not rounded

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2020#104]
## Kind (Required)

Choose the suitable template if exists.

- Other

 ## Overview (Required)

- Title says it all.  

 ## Screenshot	
<img src="https://user-images.githubusercontent.com/13705006/72199409-f9d17980-347e-11ea-9f70-f7c8bc3a090f.png" width="300px">

**Comment by koogawa** [comment]
I think this is default behavior 🤔 
https://github.com/material-components/material-components-android/pull/437

Should I fix this issue? 😃

**Comment by takahirom** [comment]
I checked with the designer. Since this is a feature of the app, I want to put it in.

**Comment by Dai1678** [comment]
@takahirom 
✋
I have two ideas.
1. use BottomSheetBehavior.addBottomSheetCallback and adjust topLeft radius.
https://github.com/material-components/material-components-android/pull/437#issuecomment-536734312
2. create shape background and attach to fragment_bottom_sheet_sessions's constraintLayout (such as DroidKaigi2019 app). Not use Widget.DroidKaigi.BottomSheet.

Which is best solution?

**Comment by takahirom** [comment]
@Dai1678 Thanks for the idea!!
The first one seems to be good because it can get on the mechanism of the component.

**Comment by Dai1678** [comment]
Thank you. I wiil try this issue.

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by Dai1678** [comment]
すみません。意図を全部英語で正しく伝えきるのが難しいので日本語で失礼します...

> use BottomSheetBehavior.addBottomSheetCallback and adjust topLeft radius.

支持頂いたこちらの方法で実装してみているのですが、上手くいかない状況でヘルプを頂きたいです

左上の角のみを調整するのに`MaterialShapeDrawable`を使って実装してみているのですが、以下の問題点が発生してしまっています
- 常に角は丸い仕様なので、`addBottomSheetCallback`内ではなく`onViewCreated`の直後でレイアウトに対して`MaterialShapeDrawable`をセットするようにしたが、`MaterialShapeDrawable`が適用されない (メソッドは呼ばれている)
- `background`に`materialShapeDrawable`を設定すると、そのレイアウトに設定されていたstyle(もしくはbackgroundTintのみ?)が無視されるので setTintで`R.attr.colorSurface`を適用したが、ダークモード時の色が以前と変わってしまった
(`Widget.MaterialComponents.BottomSheet`の`backgroundTint`で定義されている値が`colorSurface`だったので使用)

作業中のコード
https://github.com/Dai1678/conference-app-2020/blob/ba1ece7bbfac32facaf64ed642deebc954738b09/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt#L273-L288

|ライトモード|ダークモード|
|---|---|
|<img src="https://user-images.githubusercontent.com/19250035/72642303-5ec12e00-39af-11ea-949d-9777e730d9ae.gif" width=300 />|<img src="https://user-images.githubusercontent.com/19250035/72642879-b744fb00-39b0-11ea-8b25-f14390120cfe.gif" width=300 />|

つたない文章で申し訳ありませんがご確認頂けると助かります。
他に良い方法があればご教授頂きたいです。

**Comment by NUmeroAndDev** [comment]
@Dai1678 
How about use `MaterialShapeDrawable.createWithElevationOverlay` ?

Like this ↓
```
val materialShapeDrawable = MaterialShapeDrawable.createWithElevationOverlay(requireActivity(), elevation).apply {
    setShapeAppearanceModel(shapeAppearanceModel)
}
```

**Comment by NUmeroAndDev** [comment]
@Dai1678 
I think the first problem can be solved by setting shapeAppearance to null.

```
<style name="Widget.DroidKaigi.BottomSheet" parent="Widget.MaterialComponents.BottomSheet">
    <item name="shapeAppearance">@null</item>
</style>
```

`materialBackground` that `BottomSheetBehavior` has is not overwritten by setBackground.

**Comment by Dai1678** [comment]
@NUmeroAndDev 
Thank you for reply!!!

All your suggestions worked correctly.
I will create fix PR.
