### ISSUE TITLE
Add search item index and sort items.

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#107]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add search item index of speaker and session.
  - The same index is displayed only once. 
  - The index is displayed in the same way as the time in the timetable.
- Sort by speaker name, session title.

<img src=https://user-images.githubusercontent.com/6636072/72200041-c8a97700-3487-11ea-81a9-bccff673bd6a.png  width=50%>
<img src=https://user-images.githubusercontent.com/6636072/72200044-ca733a80-3487-11ea-8fbd-ac80fb4a4505.png  width=50%>

 ## Links	

-

**Comment by Pluu** [comment]
🙋🏻‍♂️

**Comment by FujiKinaga** [comment]
@Pluu 
Thanks again! Assigned 👍
