### ISSUE TITLE
Add search icon tap feedback

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#110]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add search icon tap feedback

<img src=https://user-images.githubusercontent.com/6636072/72200264-c4cb2400-348a-11ea-9b4a-3e19790e4653.png  width=50%>

 ## Links	

-

**Comment by OldBigBuddha** [comment]
🙋‍♀️

**Comment by e10dokup** [comment]
@OldBigBuddha Thanks! assigned 🙏 💪

**Comment by e10dokup** [comment]
@OldBigBuddha I close this issue because #316 already fixed. If you would like, please challenge other issues!
