### ISSUE TITLE
Add menu icon tap feedback

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#111]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add menu icon tap feedback
- Change highlight to the same color as the tab highlight

<img src=https://user-images.githubusercontent.com/6636072/72200317-81bd8080-348b-11ea-8ca9-e4fda68280cc.png  width=50%>

 ## Links	

-

**Comment by kenjikitamura** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Assigned🎨
