### ISSUE TITLE
When BottomSheet is collapsed, sub header label should change.

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#112]
## Kind (Required)

- Improvement

 ## Overview (Required)

- When the back layer is active, change sub header design

 ## Links	

- https://material.io/components/backdrop/

## Screenshot
Current | Design
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72200312-5fc3fe00-348b-11ea-9a70-e81c0c029e35.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/27717556/72200333-a74a8a00-348b-11ea-880f-93d139882a04.png" width="300px" />

**Comment by okuzawats** [comment]
i will try

**Comment by satsukies** [comment]
@okuzawats 
Thank you! Assigned 👍
