### ISSUE TITLE
Change icon color on SearchView

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#113]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Change right icon color on SearchView. change to `colorPrimary`.

<img src=https://user-images.githubusercontent.com/6636072/72200359-e7aa0800-348b-11ea-82da-7d3c778b040b.png  width=50%>
<img src=https://user-images.githubusercontent.com/6636072/72200417-a108dd80-348c-11ea-9faa-a1cb49963796.png  width=50%>

 ## Links	

-

**Comment by nishinotakuma** [comment]
🙋

**Comment by takahirom** [comment]
Assigned🔎
