### ISSUE TITLE
Add bottom margin to search

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#114]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add bottom margin to search.  See red rectangle.

<img src=https://user-images.githubusercontent.com/6636072/72200461-268c8d80-348d-11ea-828b-815608a170ec.png  width=50%>

 ## Links	

-

**Comment by Takafumi-Orita** [comment]
🙋

**Comment by takahirom** [comment]
Assigned 👍

**Comment by Takafumi-Orita** [comment]
Do I need to change the margin size when using gesture navigation?

**Comment by takahirom** [comment]
You can use `insets.systemWindowInsetBottom` like this 🙏 
https://github.com/DroidKaigi/conference-app-2020/blob/master/android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt#L99
