### ISSUE TITLE
Add emptyView in my favorite sessions screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#116]
## Kind (Required)

- Other

 ## Overview (Required)
- add empty view when you have not favorite session yet
- please confirm `BottomSheetFavoriteSessionsFragment.kt`

## Screenshot
<img src="https://user-images.githubusercontent.com/27717556/72200515-ab77a700-348d-11ea-96a9-0183602738f5.png" width="300px">

**Comment by Hunachi** [comment]
🙋

**Comment by takahirom** [comment]
Assigned🙏
