### ISSUE TITLE
Sessions are not displayed on Android 5.0

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#117]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/72200544-175a0f80-348e-11ea-8611-e960a94d3ca7.png)

 ## Links	

- Is this related?? https://github.com/DroidKaigi/conference-app-2020/blob/e1db7b4899bcdad27b3f50ad7fb7d68fade81129/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetDaySessionsFragment.kt#L92

**Comment by keikyukyun** [comment]
I try it✋

**Comment by FujiKinaga** [comment]
@keikyukyun 
I'm sorry for the late reply😭
Assigned! 👍

**Comment by FujiKinaga** [comment]
@keikyukyun 
Hi.  
This issue may be already fixed in latest build because I think that it's related to be merged #398   
How do you think about?
If you can't reproduce, let me close!

**Comment by keikyukyun** [comment]
@FujiKinaga 
Hi.
I’m so sorry for the late reply.
I’ve checked, but it still seems to be a problem in my environment.

**Comment by FujiKinaga** [comment]
@keikyukyun 
Thanks for your response.
I see..
I'll keep this issue!👍

**Comment by nukka123** [comment]
@keikyukyun @takahirom 

I've found one workaround.
Add `binding.executePendingBindings()` to `sessionsViewModel.uiModel.observe()`'s `onChanged`.
It seems can improve this issue.
However sorry, I don't know the exact reason... 😢 

再現時の動作を解析したところでは、`groupAdapter.update()`には 35個の`SessionItem`が期待通りに渡されていますが、`SessionItem`の`bind()` が呼ばれていない状況のようです。
そのため `GroupieAdapter`または`RecyclerView`のデータ更新 あるいは Viewの描画更新 に関する何かが、上手に機能していないと推測しています。

**Comment by takahirom** [comment]
@nukka123 
Add binding.sessionRecycler.scrollBy(0, 0) instead of binding.executePendingBindings()
It works!
調べてみたのですが、onLayoutがFragmentContainerViewから下のレイアウトに来ていないみたいで、レイアウトがされしだい動くみたいです。
手でスクロールしたときに動くのがRecyclerView.consumePendingUpdateOperations()でそれを手軽に呼べるのがscrollBy(0, 0)というわけです。

**Comment by keikyukyun** [comment]
@takahirom @FujiKinaga 
I'v checked this.
This issue is resolved!
Can I closed this issue??

**Comment by takahirom** [comment]
Thanks !!
