### ISSUE TITLE
Filters are not exists on Android 5.0

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#118]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 

![image](https://user-images.githubusercontent.com/1386930/72200582-a109dd00-348e-11ea-8d36-e31ad91aff26.png)

**Comment by gen0083** [comment]
filters are shown but need some long times or need to move day1-day2 etc...
attached screenshot on Android5.0 with emulator.
(probably same on Android 5.1.1)

![Screenshot_1579164537](https://user-images.githubusercontent.com/7608725/72508265-bf098000-3888-11ea-8652-273b688dc637.jpg)

**Comment by crimsonwoods** [comment]
@takahirom Maybe, I found the workaround to fix this issue. Would you assign me?

**Comment by takahirom** [comment]
Thanks Assigned 👍
