### ISSUE TITLE
Should adjust the initial position of a time text at session list screen

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#119]
## Kind (Required)
Improvement

 ## Overview (Required)
When scrolling up the list, there is a margin to go up slightly, so it is better to adjust the initial position of the time text.
<img src="https://user-images.githubusercontent.com/33515193/72200566-5e480500-348e-11ea-9533-540413c8a1e1.gif" width="320px">

 ## Links	
none

**Comment by 5hyn3** [comment]
🙋‍♂

**Comment by roana0229** [comment]
Assigned 👍

**Comment by FujiKinaga** [comment]
I'll close this issue so it seems to be fixed by #239 😁
