### ISSUE TITLE
Should disable clickable labels at session detail screen

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#120]
## Kind (Required)
Improvement

 ## Overview (Required)
![screencast 2020-01-11 16-28-57](https://user-images.githubusercontent.com/33515193/72200705-f4c8f600-348f-11ea-8aa4-1e00e9f246af.gif)

 ## Links	
none

**Comment by shcahill** [comment]
🤚

**Comment by jmatsu** [comment]
Thanks! assigned to you. Please feel free to ask us if you have any questions.
