### ISSUE TITLE
Status bar color disappears when switching DarkTheme

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#121]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Occurs when changed from dark to light

<img src=https://user-images.githubusercontent.com/6636072/72200687-c8ad7500-348f-11ea-9da9-6297cf12a61f.gif  width=50%>
<img src=https://user-images.githubusercontent.com/6636072/72200698-dd8a0880-348f-11ea-8936-fde6c9bb8c70.png  width=50%>

 ## Links	

-

**Comment by kwmt** [comment]
Let me try 🙋

**Comment by satsukies** [comment]
Thanks!! Assigned :+1:
