### ISSUE TITLE
Favorite is not applied on Android 5.0

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#122]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably the favorite state applied to session, but not shown.
![favorite_not_applied](https://user-images.githubusercontent.com/1386930/72200711-fe525e00-348f-11ea-9994-38a87fae9c6c.gif)

 ## Links	

-

**Comment by eyedol** [comment]
I'll take this. Could you assign it to me?

**Comment by roana0229** [comment]
Assigned 👍

**Comment by eyedol** [comment]
In progress...

**Comment by eyedol** [comment]
I need a little help if anyone has experienced this before. So the  `session.isFavorited` field is updated correctly when the user taps on the favorite icon however the favorite icon state is not updated right away until the user scrolls up or down the screen or navigate away and comes back. I'm suspecting something with GroupAdapter is not updating the Recyclerview items correctly. This is specific to Android 5.0 as the ticket says. I'll keep debugging in the meantime.

**Comment by takahirom** [comment]
Thank you for investigating! 👍 
If you want to give up, you can unassign the issue.

**Comment by eyedol** [comment]
@takahirom  not yet :)
