### ISSUE TITLE
The language of the announcement should also change dynamically when switching languages

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#124]
## Kind (Required)
Improvement

 ## Overview (Required)
I think that the language of the announcement should also change dynamically when switching devices language.
<img src="https://user-images.githubusercontent.com/33515193/72200812-2e4e3100-3491-11ea-8ba4-b397258ae90a.gif" width="320px">

 ## Links	
none

**Comment by chigichan24** [comment]
I want to try this issue🙋

**Comment by satsukies** [comment]
Thanks! Assigned :+1:
