### ISSUE TITLE
Filter vertical margin is required

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#127]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/72201027-4626b480-3493-11ea-97fd-b9ae9ed9a775.png)

![image](https://user-images.githubusercontent.com/1386930/72200991-05c73680-3493-11ea-9511-7c4fb8202a54.png)

**Comment by sadashi-ota** [comment]
🙋‍♂

**Comment by roana0229** [comment]
Assigned 👍
