### ISSUE TITLE
Wrong touch feedback for TabLayout

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#128]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I think it should be square ripple feedback.
![touch_feedback](https://user-images.githubusercontent.com/1386930/72201063-9867d580-3493-11ea-975e-e67de6f49a94.gif)

**Comment by NUmeroAndDev** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Thanks!!
