### ISSUE TITLE
Add named argument for StartTimeText

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#129]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add named arguments for StartTimeText
- It is very easy 😄 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/c4541d4948c0f8eef238f1e02ce7842e3ac4a9a8/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt#L75-L77

**Comment by sdfadsfsdf** [comment]
🙋‍♂

**Comment by jmatsu** [comment]
assigned. thank you so much! please tell us if you have any questions.

**Comment by sdfadsfsdf** [comment]
https://github.com/DroidKaigi/conference-app-2020/pull/234
@jmatsu Already finished?

**Comment by jmatsu** [comment]
Oh sorry, I haven't noticed it. It sounds this issue is gonna be fixed in #234

**Comment by jmatsu** [comment]
@sdfadsfsdf 
Sorry for confusing you. Could you please handle this issue? It looks the PR has been closed anyway.
