### ISSUE TITLE
Add filter margin start and end

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#130]
## Kind (Required)

- Improvement

 ## Overview (Required)

![image](https://user-images.githubusercontent.com/1386930/72201206-eb8e5800-3494-11ea-94cb-d00aff2d1c09.png)

 ## Links	

- We can use guideline 😄  https://github.com/DroidKaigi/conference-app-2020/blob/7a738455f7beefd7beb9db77b755298da6af9c4a/feature/session/src/main/res/layout/fragment_sessions.xml#L31-L44

**Comment by ham-burger** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Assigned↔️
