### ISSUE TITLE
Add tap feedback navigating speaker detail

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#131]
## Kind (Required)

- Improvement

 ## Overview (Required)

- add tap feedback when tap user view for navigating.
- you can navigate there if set `app:destination="@id/speaker"` at action tag in `navigation.xml`

## Screenshot
<img src=https://user-images.githubusercontent.com/27717556/72201252-5049b280-3495-11ea-9565-037db5039311.png  width="300px">

**Comment by rnitame** [comment]
🙋‍♂

**Comment by FujiKinaga** [comment]
Thanks! Assigned! 🙇‍♂️
