### ISSUE TITLE
Place holder color should be colorPrimary on Android 5.0

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#132]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Place holder color is should be colorPrimary on Android 5.0

![image](https://user-images.githubusercontent.com/1386930/72201347-57bd8b80-3496-11ea-9242-f1ed5fcf38f3.png)

 ## Links	

-

**Comment by nukka123** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Thanks! Assigned 🙇

**Comment by nukka123** [comment]
investigation result.

`ContextCompat.getColor(context, R.color.speaker_icon)` returns `0xFFFF0000`.
`speaker_icon` uses style attributes (`?colorPrimary`).
However, `getColor` can not resolve style attributes, if below Android M.

I found following article.
https://www.androiddesignpatterns.com/2016/08/contextcompat-getcolor-getdrawable.html

There are explained to use `AppCompatResources.getColorStateList`.

**Comment by takahirom** [comment]
Thank you.  It may be a good idea not to use a theme, and it may be good to divide it as v23.  Is there any recommended way?🎨

**Comment by nukka123** [comment]
I propose to use `AppCompatResources.getColorStateList()`.
It can resolve style attributes even if below Android M.
We can keep aware a color theming.
Please check the PR.
