### ISSUE TITLE
Key board is not hidden when back from search by button

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#133]
## Kind (Required)

- Improvement

 ## Overview (Required)

- If you move screen while the keyboard is displayed, the keyboard will not be hidden.
- Hide keyboard when moved.

![keyboard_not_hidden_when_back](https://user-images.githubusercontent.com/1386930/72201433-3dd07880-3497-11ea-85e7-3ae806e4a7e0.gif)

 ## Links	

-

**Comment by kumamotone** [comment]
🙋‍♂

**Comment by roana0229** [comment]
@kumamotone Thanks, assigned!
