### ISSUE TITLE
iOS App session list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#134]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Probably you can access sessions now by Kotlin Native
https://github.com/DroidKaigi/conference-app-2020/blob/master/ios-base/DroidKaigi%202020/ViewController.swift#L17
- You can introduce RxSwift etc. You can design iOS App Architecture 😄 

 ## Links	

-

**Comment by ry-itto** [comment]
I want to try this ✋

**Comment by takahirom** [comment]
🍎Thanks! 🍎
