### ISSUE TITLE
iOS App introduce Material Component

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#135]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- It can not be exactly the same, but it can be closer to the Android app design. You can use the Android app design.

 ## Links	

- https://github.com/material-components/material-components-ios

**Comment by takahirom** [comment]
We don't think iOS and Android should have the same design.  I think that we can optimize well by riding on the framework of material components.  I'm sorry if you misunderstand.

**Comment by 4074** [comment]
I got it.
Thanks for your sharing the guidelines. It is so useful to me.

**Comment by cutmail** [comment]
🙋‍♂

**Comment by yurihondo** [comment]
Thanks! assigned!!
