### ISSUE TITLE
iOS App announcement list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#136]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- You can fetch announcment `ApiComponentKt.generateDroidKaigiApi().getAnnouncementsAsync`
- https://github.com/DroidKaigi/conference-app-2020/blob/c4541d4948c0f8eef238f1e02ce7842e3ac4a9a8/ios-base/DroidKaigi%202020/ViewController.swift#L17
![image](https://user-images.githubusercontent.com/1386930/72201734-7756b300-349a-11ea-88e8-a409ba27a173.png)

 ## Links	

-

**Comment by yuta24** [comment]
I try 🙋‍♂

**Comment by roana0229** [comment]
Assigned 👍
