### ISSUE TITLE
The navigation bar transparency is lost

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#138]
## Kind (Required)
Improvement

 ## Overview (Required)
The navigation bar loses transparency when reconfigured screen by settings are changed.
There is almost no user impact, however I'm glad if improve it.

<img src="https://user-images.githubusercontent.com/33515193/72204186-86e4f480-34b8-11ea-96b8-b9cf9717baf4.gif" width="320px">

 ## Links	
none

**Comment by ttanaka330** [comment]
I tried to address this issue, but it seems to have been resolved in #256.

**Comment by takahirom** [comment]
Thank you for your reporting!🙏
