### ISSUE TITLE
Should adjust a speaker view touch area at the session list screen

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#140]
## Kind (Required)
Improvement

 ## Overview (Required)
I think that should adjust the touch area of the speaker view because occurs many touch miss.
<img src="https://user-images.githubusercontent.com/33515193/72204854-bcd9a700-34bf-11ea-92c0-0228d8d2ae27.gif" width="320px">

 ## Links	
none

**Comment by imsaku** [comment]
Can I try to do this?🙋

**Comment by yurihondo** [comment]
Thanks Assigned!

**Comment by takahirom** [comment]
Of course🔥
