### ISSUE TITLE
Should adjust line spacing at session detail screen

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#141]
## Kind (Required)
Improvement

 ## Overview (Required)
I think that should adjust line spacing at session detail screen.
<img width="333" alt="Android Emulator - Pixel_3a_API_29:5554 2020-01-11 22-27-33" src="https://user-images.githubusercontent.com/33515193/72205539-a5062100-34c7-11ea-91dd-382f443f8424.png">

 ## Links	
none

**Comment by kako351** [comment]
🙋‍♂

**Comment by roana0229** [comment]
Assigned 👍

**Comment by FujiKinaga** [comment]
@kako351 
Hi.
This issue seems to already be fixed in latest build...😭
If you do not mind, could I close this issue?

**Comment by kako351** [comment]
OK!Thank you for reporting.
But I can't seem to close.

<img width="370" alt="スクリーンショット 2020-01-24 10 10 04" src="https://user-images.githubusercontent.com/33022494/73037264-b967f780-3e91-11ea-829c-5b3958a36fa3.png">

@yurihondo If you do not mind, could I close this issue?

**Comment by ytRino** [comment]
Closing. Thanks!
