### ISSUE TITLE
Show notification when my session starts

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#144]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Title says everything ⏲
- Probably we can use implementation of 2019.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/pull/437

**Comment by Daishin16** [comment]
🙋
I want to challenge how far I can do it !
I'll try to do my best so please help me !

**Comment by takahirom** [comment]
Assigned!
Good luck 😆
If you have any questions, please let me know👍

**Comment by Daishin16** [comment]
What was the goal of this issue this time and how far was it in the previous ㏚?

**Comment by takahirom** [comment]
The goal of this issue is to be able to see notifications when you change your device's time to the start of your favorite session of the day.
Or, Does that mean the deadline?

**Comment by Daishin16** [comment]
Thank you for your reply. 
It would be helpful if you could tell me if there is a deadline

**Comment by takahirom** [comment]
It is ok if it can be done by the beginning of February. 📆 
However, this feature sets an alarm when you like it, so those who like it now can't receive notifications, so it's nice to be there early. 😅

**Comment by Daishin16** [comment]
Compile now works. Have you seen my repository once?
https://github.com/Daishin16/conference-app-2020/tree/show-notification-when-mysession-starts/feature/notification/src/main/java/io/github/droidkaigi/confsched2020/notification

**Comment by takahirom** [comment]
Thank you 🙏
Can you create WIP(work in progress) pull request?
[WIP]Show notification when my session starts

Because there are many PRs🙇

**Comment by takahirom** [comment]
Or you can create  Draft PR

**Comment by takahirom** [comment]
I am looking for someone to challenge this issue 🔥

**Comment by eyedol** [comment]
I'd like to take it. assing it to me

**Comment by roana0229** [comment]
Thanks, assigned 👍

**Comment by eyedol** [comment]
In progress...
