### ISSUE TITLE
Add deeplink support

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#146]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We should add a deep link to here for the announcement screen.
- I want to use the navigation component deep link support
- Probably you can check it like this

```
adb shell am start -a android.intent.action.VIEW -d "https://droidkaigi.jp/2019/announcement"
```

**Comment by KoutaMatsushita** [comment]
:raising_hand:

**Comment by satsukies** [comment]
Thanks!! Assigned :bow::pray:
