### ISSUE TITLE
Use DynamicNavHostFragment and DefaultProgressFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#147]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably we can use it.
- Please try it 🚀 

 ## Links	

- https://developer.android.com/guide/navigation/navigation-dynamic

**Comment by hiraok** [comment]
i'm interested in DFMs. i wanna try it ✋ 

 It may take some time.. 😅

**Comment by takahirom** [comment]
Thanks!! Assigned 🙏

**Comment by takahirom** [comment]
@hiraok 
Are you already starting the implementation? He seems to be able to implement it. 🙇 
https://twitter.com/STAR_ZERO/status/1218441329501294592

**Comment by hiraok** [comment]
@takahirom 
Oh.. Thank you for the information. 
I started doing it, but it looks like it's done, so I'll do another issue

**Comment by FujiKinaga** [comment]
This issue seems to be related to #147 😉
