### ISSUE TITLE
Introduce LeakCanary

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#149]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I want to check for leaks by introducing LeakCanary. 🐦

**Comment by TomoyaShibata** [comment]
🙋‍♂

**Comment by NUmeroAndDev** [comment]
@TomoyaShibata 
Thanks! Assigned 🙏

**Comment by takahirom** [comment]
Assigned :eagle:
