### ISSUE TITLE
Show current time session when loading session first in Fragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#150]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We want to show the current time session when the conference starts 📜 
- We want to scroll to the current session when first loading.
- I think we can add ViewModel property shouldScrollCurrentTime: LiveData<Boolean> = MutableLiveData(true). And when scroll to the current time, we can change that LiveData value

**Comment by surajsau** [comment]
🙋‍♂

**Comment by satsukies** [comment]
Thank you! Assigned 👍

**Comment by surajsau** [comment]
Will we be showing a button saying 'Ongoing session' in the UI clicking which it'll scroll to the ongoing session? Or will we by default take the user to the current session ?

**Comment by takahirom** [comment]
@surajsau 
We will take the user to the current session by default 👍
