### ISSUE TITLE
Fix fragment view leaks

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#153]
## Kind (Required)

- Improvement

 ## Overview (Required)

- When the Fragment is on the stack, it seems to be leaking because the DataBinding field of the Fragment exists 🦅 
 - It's best to do this after fixing the issue in #149.

**Comment by TomoyaShibata** [comment]
🙋‍♂

**Comment by NUmeroAndDev** [comment]
Assigned 👍
