### ISSUE TITLE
Add ViewModel test for session list screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#154]
## Overview (Required)
The title says everything. 💯 
You can implement it in a similar way to SessionDetailViewModelTest.
https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionDetailViewModelTest.kt

## Links
https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModel.kt

**Comment by iwahara** [comment]
🙌

**Comment by takahirom** [comment]
Thanks! Assigned :raised_hands:
