### ISSUE TITLE
Add ViewModel test for session search screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#155]
## Overview (Required)
The title says everything. 💯 
You can implement it in a similar way to SessionDetailViewModelTest.
https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionDetailViewModelTest.kt

## Links
https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SearchSessionsViewModel.kt

**Comment by sdsd08013** [comment]
🙋‍♂

**Comment by mhidaka** [comment]
Assigned 👍

**Comment by FujiKinaga** [comment]
Fixed by #373 💯
