### ISSUE TITLE
Add ViewModel test for announcement screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#159]
## Overview (Required)
The title says everything. 💯 
You can implement it in a similar way to SessionDetailViewModelTest.
https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionDetailViewModelTest.kt

## Links
- https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/AnnouncementViewModel.kt

**Comment by takas125** [comment]
🙌

**Comment by takahirom** [comment]
Assigned 👍

**Comment by FujiKinaga** [comment]
I'll close so it seems to be fixed by #311 ! 💨
