### ISSUE TITLE
Add ViewModel test for contributor list screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#160]
## Overview (Required)
The title says everything. 💯 
You can implement it in a similar way to SessionDetailViewModelTest.
https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionDetailViewModelTest.kt
Blocked by https://github.com/DroidKaigi/conference-app-2020/issues/49
## Links

**Comment by takathemax** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Assigned🙏
