### ISSUE TITLE
Add a link from the BottomAppBar in the session details to the floor map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#162]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Just open the FloorMapFragment. 🗺 
![image](https://user-images.githubusercontent.com/1386930/72214884-797a4980-354e-11ea-9abe-e0b3a838b98f.png)

 ## Links	

-

**Comment by kkt-yu** [comment]
🙋

**Comment by yurihondo** [comment]
Thanks Assigned 🙏
