### ISSUE TITLE
Make sessions available for calendaring

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#163]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It is more convenient to be able to register to Google Calendar.
![image](https://user-images.githubusercontent.com/1386930/72214919-07eecb00-354f-11ea-8b15-4f3820a92fe7.png)

 ## Links	

-

**Comment by furusin** [comment]
I'm in 🙋 
What's the goal of this issue? Should call google Calendar API?

**Comment by takahirom** [comment]
I think you can use the Intent for registar calendar.✈️
