### ISSUE TITLE
Add presentation material for session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#164]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Display a disabled link even if there is no material yet.
![image](https://user-images.githubusercontent.com/1386930/72214992-3faa4280-3550-11ea-9e70-1ccfaca2510f.png)

 ## Links	

-

**Comment by MasayukiSuda** [comment]
🙋

**Comment by takahirom** [comment]
Assigned📝
