### ISSUE TITLE
Enable to expand session details

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#165]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We should collapse session detail text 📜 

- design
![image](https://user-images.githubusercontent.com/1386930/72215062-5f8e3600-3551-11ea-884e-befef557cc33.png)

 ## Links	

-

**Comment by syo-sa1982** [comment]
🙋

**Comment by yurihondo** [comment]
Thanks Assigined 🙇
