### ISSUE TITLE
Fix LocaledString in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#167]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything 😅 
![image](https://user-images.githubusercontent.com/1386930/72215203-68800700-3553-11ea-9ea1-daebdb226688.png)

 ## Links	

-

**Comment by shinya-takano** [comment]
try now...

**Comment by takahirom** [comment]
Thanks!Assigned :abcd:
