### ISSUE TITLE
Change to an easy-to-understand error message

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#170]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This is the current message. Probably we should use text as "Connection attempt failed. Please try again."
![image](https://user-images.githubusercontent.com/1386930/72215327-0e804100-3555-11ea-84d1-befa7a92e247.png)

 - You can change error messages here. https://github.com/DroidKaigi/conference-app-2020/blob/master/corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ext/AppErrors.kt#L34

 ## Links	

-

**Comment by felix925** [comment]
🤚

**Comment by yurihondo** [comment]
Assigned 🙏

**Comment by felix925** [comment]
Should I look for other issues?

**Comment by felix925** [comment]
Can I solve this problem?
Or should I contribute to other issues in this app?

**Comment by takahirom** [comment]
If you can not this issue, you can give up anytime :wink:

**Comment by felix925** [comment]
Thank you. I solving it soon.
