### ISSUE TITLE
Snackbar overlays the system UI

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#171]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably we should create a snack bar layout for showing a snack bar..? 🤔 

-  ![image](https://user-images.githubusercontent.com/1386930/72215327-0e804100-3555-11ea-84d1-befa7a92e247.png)

 ## Links	

-

**Comment by fornewid** [comment]
I think, this issue cannot be possible. :sob: 
'cause navigation bar is owned by SystemUI (system app)
and the window type is extremely high. (Over the status bar)
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/WindowManager.java#982

**Comment by takahirom** [comment]
I think we can use the margin for preventing overlay 👀

**Comment by fornewid** [comment]
:scream: so sorry, I misunderstood this issue.
The following is current state,
and snack bar should be shown above the nav bar. Right? 😃 

![Screenshot_20200115-130903~2](https://user-images.githubusercontent.com/3405740/72404502-e84ae300-3798-11ea-80b8-060e7d2b6c91.png)

**Comment by takahirom** [comment]
> snack bar should be shown above the nav bar

Yes!!

**Comment by orimomo** [comment]
Can I try it?　|・ω・*)

**Comment by jmatsu** [comment]
yes, please! thank u so much~

**Comment by orimomo** [comment]
Is this issue already fixed in master-branch?😮

<img src="https://user-images.githubusercontent.com/12453846/72660799-f6f1fe00-3a15-11ea-9d6b-1044ac0606b6.png" width="320"/>

**Comment by orimomo** [comment]
@takahirom @jmatsu 
I think this issue can be closed,  but what do you think?

**Comment by takahirom** [comment]
@orimomo Thank you for reporting.
I checked this. Probably it is fixed! Thanks!
