### ISSUE TITLE
Incremental annotation processing

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#173]
## Kind (Required)

- Improvement

 ## Overview (Required)

- When ./gradlew assembleDebug. I can see this warning. Probably we can use Incremental annotation processing

```
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
```

https://developer.android.com/jetpack/androidx/releases/room

 ## Links	

-

**Comment by Pluu** [comment]
🙋🏻‍♂️

**Comment by yurihondo** [comment]
Assigned 🙇
