### ISSUE TITLE
Add auto link support for session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#181]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/72218131-f0c5d280-357a-11ea-9842-8701a584450d.png)

 ## Links	

- You can see implementation for a speaker detail for your reference https://github.com/DroidKaigi/conference-app-2020/blob/b6a92c302839309a53538807214aa7c967f96112/feature/session/src/main/res/layout/fragment_speaker.xml#L114

**Comment by masaibar** [comment]
🤚

**Comment by roana0229** [comment]
Thanks, assigned!
