### ISSUE TITLE
Reduce image size of README 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#186]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Current images are uploaded in 
https://github.com/DroidKaigi/conference-app-2020/issues/74#issuecomment-573555849

- Those images are bigger than specified by the width of the `img` tag.
- I want to reduce the size of it

 ## Links	

-

**Comment by MasayukiSuda** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Assigned🙏🙏🙏

**Comment by FujiKinaga** [comment]
Fixed by #221 💯
