### ISSUE TITLE
Remove JvmStatic for `@Provide` methods

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#195]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably now we can delete it 😄 

 ## Links	

- https://youtu.be/o-ins1nvbDg?t=623

**Comment by phicdy** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks for taking the issue immediately!
Assigned!

**Comment by takahirom** [comment]
@phicdy 
Sorry 🙇 
Another person has worked. If you haven't started, can I give the task to that person?

**Comment by phicdy** [comment]
@takahirom Oh, ok. No problem 👍 I’ll find other issue.

**Comment by takahirom** [comment]
Thanks!!
