### ISSUE TITLE
Transition with fade

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#196]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Android dev summit app seems to be faded at the time of screen transition. Can we do the same?

 ## Links	

- https://play.google.com/store/apps/details?id=com.google.samples.apps.adssched&hl=ja

**Comment by rmakiyama** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Thanks! Assigned!
