### ISSUE TITLE
Add shadow when scroll sessions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#198]
## Kind (Required)

- Improvement

 ## Overview (Required)

- When scroll session, we would like to add shadow to here 📜 
![image](https://user-images.githubusercontent.com/1386930/72262342-1b3a8d00-365a-11ea-982b-1436cc6117df.png)

 ## Links	

-

**Comment by rnitame** [comment]
:raising_hand_man:

**Comment by roana0229** [comment]
Assigned ! 👍
