### ISSUE TITLE
Add padding to TabLayout

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#199]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 📑 
![image](https://user-images.githubusercontent.com/1386930/72262653-b29fe000-365a-11ea-9fb2-8d9433ad153a.png)

design
![image](https://user-images.githubusercontent.com/1386930/72262714-c9463700-365a-11ea-8218-7d78163f83c8.png)

 ## Links	

-

**Comment by NUmeroAndDev** [comment]
🙋‍♂

**Comment by takahirom** [comment]
🙏
