### ISSUE TITLE
Blink time when favorite

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#202]
## Kind (Required)

- Improvement

 ## Overview (Required)

- ⏲ 
![like_time](https://user-images.githubusercontent.com/1386930/72264431-1b3c8c00-365e-11ea-9e01-6500d5f8fb8b.gif)

 ## Links	

-

**Comment by yt8492** [comment]
This issue means time should not be blink when user favorite, right? Time should be invisible?
(I want to make it clear. I worry about I'm misunderstanding issue)

**Comment by takahirom** [comment]
Thanks! I want to remome blink the time text!

**Comment by yt8492** [comment]
Thank you for replying! I will try this issue.

**Comment by takahirom** [comment]
Thanks! Assigned
