### ISSUE TITLE
When landscape, we can not show the navigation drawer

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#203]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We should apply window inset
![image](https://user-images.githubusercontent.com/1386930/72265462-e6313900-365f-11ea-8731-4ba7b0ccac7d.png)

 ## Links	

-

**Comment by fornewid** [comment]
I want to try this. :hand:
Please assign to me.

**Comment by takahirom** [comment]
Thanks!Assigned🙏
