### ISSUE TITLE
Wrong speakers appear after fast scrolling

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2020#229]
**Overview (Required)**
- Title says everything.

**Steps To Reproduce**

1. Lunch App.
2. Fast scroll on DAY1 or DAY2. (Up or Down)
4. Tap a any speaker name label.

**Expected behavior**
Display information is written in name speaker.
(ラベルに書かれている名前のスピーカーについての情報が表示されます)

**Screenshots**

![ezgif-6-18701df94f13](https://user-images.githubusercontent.com/13657682/72358938-b9992200-3730-11ea-8c76-d75e78f4a9bc.gif)

**Env:**
 - Device: Pixel3 XL
 - OS: 10
 - master

**Comment by ypresto** [comment]
🙌

**Comment by takahirom** [comment]
Assigned!
