### ISSUE TITLE
Need logo.png for each resolution

### ISSUE THREAD

**Issue by futabooo** [DroidKaigi/conference-app-2020#233]
## Kind (Required)
- Other

 ## Overview (Required)
- logo.png is Jaggy other  xhdpi resolution because use only xhdpi

<img src="https://user-images.githubusercontent.com/944185/72361394-03c7d680-3724-11ea-98ee-bbd7f3c88353.png" width="320">

 ## Links	

-

**Comment by ypresto** [comment]
![image](https://user-images.githubusercontent.com/400558/72371819-7ba7f800-3748-11ea-867c-5e79cc153dc7.png)

Need a frame (not a group) with right width/height (png file is 236x67) in Figma, or exporting and using it end up with out of alignment of logo (because it'll be without right margin).

**Comment by ypresto** [comment]
We can use VectorDrawable for every drawable as our minSdkVersion is 21!

**Comment by takahirom** [comment]
What doesn't look good with this method?
![image](https://user-images.githubusercontent.com/1386930/72373084-e5c19c80-374a-11ea-93c1-02bddc2ea7f0.png)

**Comment by ypresto** [comment]
Purple line (304x167) corresponds to unrelated `Account Switcher` symbol instance in another tree of a group.

![image](https://user-images.githubusercontent.com/400558/72373797-5917de00-374c-11ea-8e85-58aeb6a783c4.png)

Export 2 Layers button (in your Screen Shot) will write two of PNG files, one is Account Switcher, and another is Logo.png which has 230x61 = without margin. (see below, border is added by me)

![Logo](https://user-images.githubusercontent.com/400558/72374251-3e923480-374d-11ea-9bff-6a8a0bda1726.png)

**Comment by ypresto** [comment]
I consulted @chihokotaro in [Twitter](https://twitter.com/chihokotaro/status/1217269975867543554?s=20) and it turned out that the moved-left layout is not intended and is by mistake.

Now the layout looks like below, and we can just export `Logo` group! :tada:

![image](https://user-images.githubusercontent.com/400558/72440570-700e0d00-37ec-11ea-811e-96706f052953.png)

**Comment by ypresto** [comment]
🙌

**Comment by yurihondo** [comment]
Thanks Assigned 🙇

**Comment by ypresto** [comment]
I tried to use exported `Logo.svg` but is too complex and not ready for vector drawable (has 16 large paths and 1 unnecessary clipPath, and produced `Attribute "android:fillType" was already specified for element "path".` error in Vector Asset Studio :joy:), so I give up with VectorDrawable. I'll use bitmap format.

**Comment by ypresto** [comment]
I have forgotten about dark theme :joy:

Current state:
![image](https://user-images.githubusercontent.com/400558/72456671-7e6a2200-3808-11ea-9fb2-571f1e955104.png)


@chihokotaro Could you add a group for logo type only (see below), so we can change text color (without affecting for icon) for dark theme by drawable tinting?
![image](https://user-images.githubusercontent.com/400558/72456018-2f6fbd00-3807-11ea-86c3-757898aea07d.png)

**Comment by takahirom** [comment]
We plan to add a dark theme design this weekend.
It might be a good idea to commit with the current image, which was not optimized for the dark theme before.
