### ISSUE TITLE
Add project level dictionary for suppress typo

### ISSUE THREAD

**Issue by kyanro** [DroidKaigi/conference-app-2020#242]
## Kind (Required)
- Other

 ## Overview (Required)
Android Studio detects many typo in Dep.kt.
But I think, almost words are correct.
I want to add project level dictionary for suppress typo.

`.idea/dictionaries/Project.xml`
```
<component name="ProjectDictionaryState">
  <dictionary name="Project">
    <words>
      <w>emoji</w>
      <w>firestore</w>
      <w>jetifier</w>
       ... and more
    </words>
  </dictionary>
</component>
```

**Comment by kyanro** [comment]
🙋

**Comment by takahirom** [comment]
Thank you for creating and doing it 😄
