### ISSUE TITLE
Enable R8

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#249]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I want to optimize the app using R8🔥

 ## Links	

-

**Comment by tarumzu** [comment]
🙋‍♂🔥

**Comment by takahirom** [comment]
🔥🔥🔥🔥🔥🔥

**Comment by roana0229** [comment]
Assigned 🔥🔥

**Comment by STAR-ZERO** [comment]
I'm curious about how to test dynamic feature module applied R8. Can we use internal app sharing?

**Comment by takahirom** [comment]
Thank you! Does universal apk make the problem invisible? 👀

**Comment by STAR-ZERO** [comment]
I'm not sure but I recommend to test the app on internal app sharing or test track before the production release. Navigation to dynamic feature module uses reflection, so it's easy to occur crash.

**Comment by jmatsu** [comment]
Indeed. It's absolutely required. I'm still wondering if which distribution track is preferable, but let me integrate a service somehow.

**Comment by LeoAndo** [comment]
@takahirom @tarumzu 

AssistedInject is Disable R8's ProGuard compatibility mode.

https://github.com/square/AssistedInject/commit/984b5f80a338205e3ebf86306635d78a06141ec6#diff-503f218d646c10f484fdc9d6315bf2e3

**Comment by takahirom** [comment]
I didn't know that!😮
Does it affect to app? Not only library?👀

**Comment by tarumzu** [comment]
@LeoAndo Thank you for the link! 
I think It only affects the library.
