### ISSUE TITLE
Fix typo on arts/multimodule.png

### ISSUE THREAD

**Issue by takattata** [DroidKaigi/conference-app-2020#251]
## Kind (Required)
- Other

 ## Overview (Required)
- As is : Dinamic Feature Modules → To be : Dynamic Feature Modules

 ## Links	
-

**Comment by mhidaka** [comment]
Eagle eye!
would you like to fix it as your work?

**Comment by takattata** [comment]
thank you~
Yes, I would.

**Comment by jmatsu** [comment]
Cool! Thank you very much!

**Comment by takattata** [comment]
What the font is used in arts/multimodule.png?

**Comment by takahirom** [comment]
Can you use this image? 🙇 
![image](https://user-images.githubusercontent.com/1386930/72407803-108c0f00-37a4-11ea-923b-dd05ed617dbc.png)

**Comment by takattata** [comment]
OK! Thank you!
