### ISSUE TITLE
Gem cache not stored.

### ISSUE THREAD

**Issue by hkusu** [DroidKaigi/conference-app-2020#255]
**Overview (Required)**
- Gem cache failed in CI(GitHub Actions) at pull request.
- For example, https://github.com/DroidKaigi/conference-app-2020/runs/390543966 .

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

<img width="800" alt="スクリーンショット_2020-01-15_16_33_25" src="https://user-images.githubusercontent.com/6157540/72414361-5dc4ac80-37b5-11ea-935a-1d4f9cbd8368.png">

**Env:**

**Additional context**

Probably it should be modified as follows.

`bundle install --path=vendor/bundle --jobs=4 --clean --gemfile=.ci/Gemfile`
↓
`bundle install --path=./vendor/bundle --jobs=4 --clean --gemfile=.ci/Gemfile`

**Comment by jmatsu** [comment]
Thanks for your report. 

bundle command works as intended but the cache key seems to be wrong. The correct cache key would be `.ci/vendor/bundle`.

**Comment by Takafumi-Orita** [comment]
🙋

**Comment by roana0229** [comment]
Assigned 👍
