### ISSUE TITLE
Api call fails in announce tab if using ja for default language

### ISSUE THREAD

**Issue by chigichan24** [DroidKaigi/conference-app-2020#258]
**Overview (Required)**
- In the Announce tab, api call for `https://deploy-preview-49--droidkaigi-api-dev.netlify.com/2020/announcements/jp/index.json` fails all time. Api returns 404.
    - So always showing "お知らせなし" in this tab.
- if you use EN as default language in your device, api call successfully finished and fetched some announces.
-  I think the endpoint parameter mistook. It should be replaced https://BASE_URL/announcements/**jp** with https://BASE_URL/announcements/**ja**

**Steps To Reproduce**

1. Go to 'Announce Tab' by using ja for the default language.

**Expected behavior**
- Show some announces.

**Screenshots**

 ja | en
:--: | :--:
<img src="https://user-images.githubusercontent.com/7840108/72426556-4a254000-37cd-11ea-9790-f1e81ddc5576.png" width="300" /> | <img src="https://user-images.githubusercontent.com/7840108/72426595-5f01d380-37cd-11ea-8093-c09e2c872310.png" width="300" />

**Env:**
 - Device: Pixel3a
 - OS: 10
 - App Version or the branch: master

**Comment by takahirom** [comment]
Thanks for investigating and understandable issues 💯

**Comment by chigichan24** [comment]
I'll fix it by myself. So please assign me!
