### ISSUE TITLE
BottomAppBar hides behind nav barr on Android5.1

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2020#262]
**Overview (Required)**
- 

**Steps To Reproduce**

1. Go to some of SessionDetail
4. BottomAppBar cannot see because behind of nav bar

**Expected behavior**
show BottomAppBar above of nav bar

**Screenshots**

![device-2020-01-15-203431 2020-01-15 20_44_31](https://user-images.githubusercontent.com/7608725/72431546-70041200-37d8-11ea-8561-69b4834fc176.gif)

**Env:**
 - Device: Nexus5
 - OS: 5.1.1
 - branch master

**Comment by takahirom** [comment]
Thanks! Probably duplicated 😭 
https://github.com/DroidKaigi/conference-app-2020/issues/62
