### ISSUE TITLE
Add ripple effect to BottomSheet expand icon

### ISSUE THREAD

**Issue by okuzawats** [DroidKaigi/conference-app-2020#267]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Show ripple effect when tapped

 ## Links	

-

## Screenshot

<img src="https://user-images.githubusercontent.com/12797442/72436677-5799f480-37e4-11ea-9aaa-13a7df3b9b0f.png" width="300" />

**Comment by radioboo** [comment]
🙋‍♂️

**Comment by FujiKinaga** [comment]
@radioboo 
Thanks! Assigned🙇‍♂️

**Comment by Dai1678** [comment]
I think this problem seems to be happening again.
Because `android:background="?attr/selectableItemBackgroundBorderless"` was deleted by #309
