### ISSUE TITLE
Blink time and image when favorite status change

### ISSUE THREAD

**Issue by rmakiyama** [DroidKaigi/conference-app-2020#288]
## Kind (Required)
- Improvement

 ## Overview (Required)
When session's favorite status is changed, `SessionItem` update and call bind method. (equals returns false)

<img src="https://user-images.githubusercontent.com/7961496/72495366-d5ecaa00-3869-11ea-8857-f130c46ba26d.gif" width="300" />

 ## Links	

-

**Comment by rmakiyama** [comment]
Can I tackle this one? 😎

**Comment by takahirom** [comment]
Thank you for the issue! 👍 
But if we return false on equals. Session Icon is not applied. 👀 
Probably we should disable change animation?

**Comment by rmakiyama** [comment]
I'm sorry! 🙇  It mean when we return false on equals, speaker image crossfade.
I think we should not disable change animation as using payload.

**Comment by takahirom** [comment]
Thanks. It looks good 👍 
Assigned 🙏
