### ISSUE TITLE
Speaker Session Name not showing multiple lines in TextView

### ISSUE THREAD

**Issue by koogawa** [DroidKaigi/conference-app-2020#297]
**Overview (Required)**
- Title says it all.

**Steps To Reproduce**

1. Go to 'Speaker screen'

**Expected behavior**

showing multiple lines in TextView

**Screenshots**

<img src="https://user-images.githubusercontent.com/893643/72530016-d3ae3e00-38b1-11ea-852d-003f54eaeab1.png" width="320"/>

**Env:**
 - Device: Pixel2
 - OS: 9.0
 - master

**Comment by koogawa** [comment]
✋

**Comment by takahirom** [comment]
Good job!

**Comment by mhidaka** [comment]
@FujiKinaga Thank you for sharing your notice!

**Comment by roana0229** [comment]
already fixed. https://github.com/DroidKaigi/conference-app-2020/pull/298
