### ISSUE TITLE
Description text is clipped bottom line in speaker screen.

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#300]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please should add padding vertical edge at each textview fields.

![device-2020-01-16-223823](https://user-images.githubusercontent.com/27717556/72530653-25a39380-38b3-11ea-9823-9a5c5d293b84.png)

 ## Links	

-

**Comment by cheddar-dev** [comment]
🙋

**Comment by mhidaka** [comment]
@cheddar-dev assigned! we will be waiting for your PR 😉
