### ISSUE TITLE
Optimize layout

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#301]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  Can we remove this FrameLayout? 😄 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml#L52

**Comment by furusin** [comment]
🙋

**Comment by mhidaka** [comment]
We assigned this issue to you.
