### ISSUE TITLE
Use doOnApplyWindowInsets view parameter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#302]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I think we can use view parameter. and optimize the code.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/df7e39e63702435bb4e5b552eb1a1111e57f90f9/android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt#L97

**Comment by umechanhika** [comment]
🙋

**Comment by roana0229** [comment]
Thanks, assigned 👍
