### ISSUE TITLE
Show progress bar at random position in session detail.

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#305]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It's happening a problem that show progress bar at random position.
- Please put progress bar in out of base layout view group.

## Screenshot
Case1 | Case2
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72531180-4a4c3b00-38b4-11ea-8d5a-8c6cd2f90d8f.png" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72531181-4a4c3b00-38b4-11ea-937d-84394c8c46da.png" width="300" />

**Comment by mattukouta** [comment]
🙋‍♂️

**Comment by mhidaka** [comment]
Yeah! Please grab this issue. we assigned you!
