### ISSUE TITLE
Whole TextView padding between lines

### ISSUE THREAD

**Issue by koogawa** [DroidKaigi/conference-app-2020#306]
## Kind (Required)

- Improvement, discussion

 ## Overview (Required)

- I think we should increase the spacing between lines in whole textview.

current | figma
---- | ----
<img src="https://user-images.githubusercontent.com/893643/72531401-b6c73a00-38b4-11ea-9aca-9e2840f7a8e5.png" width="320"/> | <img src="https://user-images.githubusercontent.com/893643/72531542-0574d400-38b5-11ea-81e7-c8211c646458.png" width="320"/>

 ## Links	

- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=21%3A395
- https://developer.android.com/reference/android/widget/TextView.html#attr_android:lineSpacingExtra

**Comment by koogawa** [comment]
I want to try if needed ✋

**Comment by takahirom** [comment]
Great 🥇
