### ISSUE TITLE
Add space between speaker item

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#308]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add space between speaker item

<img src=https://user-images.githubusercontent.com/6636072/72533638-d2ccda80-38b8-11ea-98fc-2f1c0c345923.png  width=50%>

 ## Links	

-

**Comment by kiyosuke** [comment]
🙋‍♂️

**Comment by roana0229** [comment]
Assigned 👍
