### ISSUE TITLE
When BottomSheet is collapsed, sub header label should change on `MYPLAN`

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#310]
## Kind (Required)

- Improvement

 ## Overview (Required)

- My plan did not change expand icon.

<img src=https://user-images.githubusercontent.com/6636072/72534147-acf40580-38b9-11ea-998b-5f6fa56a1899.png  width=50%>
<img src=https://user-images.githubusercontent.com/6636072/72534152-af565f80-38b9-11ea-96a1-41bb70931639.png  width=50%>

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/issues/112
- https://github.com/DroidKaigi/conference-app-2020/pull/263

**Comment by sekiya9311** [comment]
🙋‍♂️

**Comment by jmatsu** [comment]
Thanks @sekiya9311 . Please feel free to ask us if you have any questions during your development.
