### ISSUE TITLE
Should show placeholder when loading user image at speaker screen.

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#313]
## Kind (Required)

- Improvement

 ## Overview (Required)

- User placeholder icon does not displayed if user is using in offline and weak network connection.
    - In the other screens, it seems to be displaying placeholder when loading.

<img src=https://user-images.githubusercontent.com/27717556/72535863-9d29f080-38bc-11ea-845f-edee54cfa855.png  width=50%>

**Comment by kazkn** [comment]
Hi, I want to try this issue. because I am assigned #317. I think to change SpeakerFragment implementation used RecyclerView.
as I will implementation this issue for preventing Conflict.
