### ISSUE TITLE
Add tap feedback navigating session detail in speaker sceren

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#316]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add tap feedback when tap session title view for navigating.

## Screenshot
<img src=https://user-images.githubusercontent.com/27717556/72536620-ed558280-38bd-11ea-9f3b-38c3dd0b8a08.png  width="300px">

 ## Links	

- #131 
- #111
- #110

**Comment by YuheiKawakami** [comment]
I'll try it ! 🙋‍♂

**Comment by roana0229** [comment]
Of course, assigned 👍
