### ISSUE TITLE
Multiple speaker sessions are not displayed on the speaker screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#317]
## Kind (Required)

- Bug report
- Improvement

 ## Overview (Required)

- When specific speaker has some sessions, session title is shown only one.
- Please change that we can visible multiple session title of each speakers.

 ## Links	
- Not good `firstOrNull` .  
- https://github.com/DroidKaigi/conference-app-2020/blob/7e4a56cc15be5cca58c7f8c70d72ad810fecb344/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SpeakerViewModel.kt#L50

**Comment by kazkn** [comment]
Hi, I want to try this issue, please.

**Comment by ymnder** [comment]
@kazkn We assigned this issue to you!
Please don't hesitate to ask us if you have any questions.
