### ISSUE TITLE
SystemViewModel has Activity

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#323]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It will cause a leak.
- Please remove the activity from SystemViewModel property
- Please add Activity to openUrl parameter

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/3bd1efc4f7272046c6ce2b5774430af1849e158d/feature/system/src/main/java/io/github/droidkaigi/confsched2020/system/ui/viewmodel/SystemViewModel.kt#L17

**Comment by kouhon** [comment]
🙋‍♂

**Comment by FujiKinaga** [comment]
@kouhon 
Thanks! Assigned 👍

**Comment by FujiKinaga** [comment]
Fixed by #350 and #342  !
