### ISSUE TITLE
Chrome Custom Tab Navigator instead of SystemViewModel.openUrl

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#324]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It looks like an article 👀 

 ## Links	

- https://proandroiddev.com/add-chrome-custom-tabs-to-the-android-navigation-component-75092ce20c6a

**Comment by fornewid** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks! Assigned🙏
