### ISSUE TITLE
Add bottom margin on MYPLAN tab

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#326]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add bottom margin on MYPLAN tab

<img src=https://user-images.githubusercontent.com/6636072/72548668-80001c80-38d2-11ea-9eb6-f998061f9d76.png  width=50%>

like `DAY1`, `DAY2` tab

<img src=https://user-images.githubusercontent.com/6636072/72548673-82627680-38d2-11ea-9f06-c25fe696c6b4.png  width=50%>

 ## Links	

-

**Comment by negishitakuro** [comment]
:raising_hand:

**Comment by FujiKinaga** [comment]
@negishitakuro 
Thanks! Assigned 👍
