### ISSUE TITLE
Create PreferenceViewModel to realize unidirectional data flow

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#329]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Would you please add ViewModel in preference module.
    - To handle `onClick` and `onCheckedChange` event.
    - To follow [the architecture](https://github.com/DroidKaigi/conference-app-2020#architecture) like unidirectional data flow.
    - To ensure scalability when features are added thanks to suggestions in the future!

 ## Links	
- https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/preference/src/main/java/io/github/droidkaigi/confsched2020/preference/ui/PreferencesFragment.kt#L23

**Comment by kuramu1108** [comment]
Hi, I would like to give it a try

**Comment by jmatsu** [comment]
Cool, thanks. Please feel free to contact us if you have any questions.
