### ISSUE TITLE
Replace Fabric Crashlytics library to Firebase

### ISSUE THREAD

**Issue by tarumzu** [DroidKaigi/conference-app-2020#332]
## Kind (Required)
- Improvement

 ## Overview (Required)
- The other day, when I worked on Crashlytics, I didn't know the existence of the Firebase library.
I want to implement it with Firebase library.

https://github.com/DroidKaigi/conference-app-2020/issues/182

 ## Links	
- https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android

**Comment by takahirom** [comment]
👍

**Comment by tarumzu** [comment]
Can I try it?

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by tarumzu** [comment]
Thanks!

**Comment by tarumzu** [comment]
@takahirom 
At present, it seems that firebase crashlytics (beta) cannot be used when already linked with fabric.

I'm sorry🙇, Can you recreate the “io.github.droidkaigi.confsched2020.debug” app?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Which should we? 👀 
![image](https://user-images.githubusercontent.com/1386930/72625846-e9446600-398c-11ea-95d3-65eae1f30812.png)

**Comment by takahirom** [comment]
I don't remember making a 2020 project with Fabric. 💭

**Comment by tarumzu** [comment]
👀!

**Comment by takahirom** [comment]
So probably should we create? "いいえ、新しいFirebaseアプリを設定します"?

**Comment by tarumzu** [comment]
@takahirom Can you temporarily invite me to a project?
I want to see it directly.
tarumzu@gmail.com
🙇

**Comment by takahirom** [comment]
Maybe you can see the same thing when you create a new project. 🙇

**Comment by tarumzu** [comment]
Successful in my environment.
Can you set up a new firebase app?

**Comment by tarumzu** [comment]
Please Check "Yes".

**Comment by takahirom** [comment]
I did it 🙏 
If it is ok, I will do that for production firebase

**Comment by tarumzu** [comment]
@takahirom Thanks!!
I was successful!!!
```
2020-01-18 01:15:53.600 31829-31857/io.github.droidkaigi.confsched2020.debug I/FirebaseCrashlytics: Crashlytics report upload complete: 5E21DDB80157-0001-7C55-0660C0C2C659
```

**Comment by takahirom** [comment]
🙌

**Comment by takahirom** [comment]
![image](https://user-images.githubusercontent.com/1386930/72627860-89e85500-3990-11ea-87a9-b3df64b8a571.png)
