### ISSUE TITLE
Change some screen's navigation menu click action

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#333]
## Kind (Required)

- Improvement

 ## Overview (Required)
- Here are the things I would like to ask a favor.
    - Please change toolbar icon.
    - When taping navigation menu, please open drawer like announce screen.

## Screenshot
Not Good | Good👍 
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72586318-a0f95980-3934-11ea-8e72-4fdbd925ae7a.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72586328-a8206780-3934-11ea-9179-4cb6a2bd0168.gif" width="300" />

**Comment by NaoyukiHamada** [comment]
Hi, I want to try this issue, please.

**Comment by KeithYokoma** [comment]
@NaoyukiHamada Thanks! Assigned this issue to you so give it a try!
