### ISSUE TITLE
Test dynamic feature module offline

### ISSUE THREAD

**Issue by STAR-ZERO** [DroidKaigi/conference-app-2020#334]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Testing dynamic feature module is so hard for contributors. Offline testing might reduce the problem. It can do using `FakeSplitInstallManager`.

 ## Links	

- [FakeSplitInstallManager](https://developer.android.com/reference/com/google/android/play/core/splitinstall/testing/FakeSplitInstallManager)
- [My blog](https://medium.com/@star_zero/fakesplitinstallmanager%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9Ftest-dynamic-delivery-offline-f9f672376bab)

**Comment by STAR-ZERO** [comment]
Please assign me 🙏

**Comment by FujiKinaga** [comment]
@STAR-ZERO 
Yes!. I assigned you 👍

**Comment by STAR-ZERO** [comment]
Sorry, I overlooked android manifest in dynamic feature module.
Dynamic feature module in the app doesn't run as on_demand. Is it right? If it's so, Fake SplitInstallManager is not needed.

**Comment by takahirom** [comment]
Yes.  It is not currently on demand.  If you can deploy and debug when you enable on-demand, you want to enable it.

**Comment by STAR-ZERO** [comment]
Ok, I'll try to turn on on-demand.

**Comment by takahirom** [comment]
Thanks as always 🙏
