### ISSUE TITLE
Text wrapping of session name

### ISSUE THREAD

**Issue by kumamotone** [DroidKaigi/conference-app-2020#335]
**Overview (Required)**
- Speaker detail screen
  - Text wrapping of session name should be enabled.

ex. `基盤作` → `基盤作り`

<img width="326" alt="スクリーンショット 2020-01-17 16 33 04" src="https://user-images.githubusercontent.com/8403570/72592989-3998d500-3947-11ea-8df5-5709b897b1b7.png">

**Comment by roana0229** [comment]
Thanks for you report 👍

**Comment by kumamotone** [comment]
Oops it's duplicated.
https://github.com/DroidKaigi/conference-app-2020/issues/297

**Comment by roana0229** [comment]
@kumamotone 
I'm sorry, I think it has already been fixed.
Is it still happening on master branch?

PR: https://github.com/DroidKaigi/conference-app-2020/pull/298
Issue: https://github.com/DroidKaigi/conference-app-2020/issues/297
