### ISSUE TITLE
There is no gem cache when a new pull request is created

### ISSUE THREAD

**Issue by hkusu** [DroidKaigi/conference-app-2020#338]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is no gem cache when a new pull request is created.

  <img width="600" alt="スクリーンショット 2020-01-17 18 13 59" src="https://user-images.githubusercontent.com/6157540/72599736-a0bd8600-3955-11ea-97a4-0140112d20d8.png">

- Because the cache of GitHub Actions searches the cache in the order of the pull request's branch, the merge destination branch, and the default branch, when creating a new branch, there is no cache, and the cache also exists in the merge destination branch(master) and the default branch(master).

- There is a cache about `~/.m2/repository`, but it seems that it was cached during the past development, so the cache will expire.

- The solution is to prepare a workflow that creates a cache when the code is pushed to the master branch.

- Can you assign me because I can solve it.

 ## Links

**Comment by takahirom** [comment]
Thanks Assigned! (by @jmatsu )

**Comment by hkusu** [comment]
This issue is no longer needed.
