### ISSUE TITLE
Close drawer when back button pressed

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2020#340]
## Kind (Required)

- Improvement

 ## Overview (Required)

- press back button when drawer open, go back home currently
- it'll be better to close drawer 

![currently 2020-01-17 21_19_21](https://user-images.githubusercontent.com/7608725/72612078-12ee9480-396f-11ea-8fa3-ccdc4fed0531.gif)

 ## Related

- #126
- #266

**Comment by YuheiKawakami** [comment]
I'll try this issue 🙋‍♂

**Comment by FujiKinaga** [comment]
@YuheiKawakami 
Thanks for raising up your hand!
Assigned 👍
