### ISSUE TITLE
Add space between speaker item on session detail screen

### ISSUE THREAD

**Issue by koogawa** [DroidKaigi/conference-app-2020#344]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add space between speaker item on session detail screen

<img src=https://user-images.githubusercontent.com/893643/72615279-adeb6c80-3977-11ea-94a9-6ecb2eb04b1e.png  width=50%>

 ## Links	

- #308

**Comment by koogawa** [comment]
✋

**Comment by roana0229** [comment]
Thanks always, assigned 👍
