### ISSUE TITLE
ViewModel values ​​except UiModel should be inaccessible from outside

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#349]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Sometimes, we can access public instances of viewModel. But many of them should be private.
- Please try look into various viewModels for refactoring! 

<img width="665" src="https://user-images.githubusercontent.com/27717556/72619335-5ef60500-3980-11ea-91e9-1d9297a16014.png">

**Comment by Pluu** [comment]
🙋🏻‍♂️

**Comment by roana0229** [comment]
Assigned 👍
