### ISSUE TITLE
Use DropBox/Store4 for DataStaffRepository

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#357]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Rather than replace, I want to try and try it once.
- You can access staffs screen  from about screen

 ## Links	

-

**Comment by omtians9425** [comment]
Can I try it???

**Comment by FujiKinaga** [comment]
@omtians9425 
Of course!👍 
I assigned you!

**Comment by FujiKinaga** [comment]
It seems to be fixed by #707, Once I'll close this issue👋
