### ISSUE TITLE
Use TypeAlias for R class

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#359]
## Kind (Required)

- Improvement

 ## Overview (Required)

- android.R
- androidx.appcompat.R

AndroidR
AppCompatR
![image](https://user-images.githubusercontent.com/1386930/72630670-2c570700-3996-11ea-9019-0dcfeee8d9f0.png)

 ## Links	

-

**Comment by rockun1** [comment]
🙋🏻‍♂️

**Comment by matsujun** [comment]
Thanks!
Assigned!

**Comment by rockun1** [comment]
Sorry if I misunderstand. I have a question.

## AndroidR.id is unresolved

In my environment(Android Studio 3.6 RC 1), 
typealias `AndroidR = android.R, AppcompatR = androidx.appcompat.R` is not working correctly.
But, these typealias `AndroidAttr = android.R.attr, AppcompatId = androidx.appcompat.R.id` is working.

#### declare typealias

<img width="498" alt="Screen Shot 2020-01-18 at 20 47 28" src="https://user-images.githubusercontent.com/11315426/72663243-ca4cdf00-3a33-11ea-98b3-edc8290c3339.png">

#### not working (search_button) 

<img width="659" alt="Screen Shot 2020-01-18 at 20 06 53" src="https://user-images.githubusercontent.com/11315426/72663269-e18bcc80-3a33-11ea-9353-853f77a65ac7.png">

#### working (search_close_button)

<img width="675" alt="Screen Shot 2020-01-18 at 20 05 25" src="https://user-images.githubusercontent.com/11315426/72663290-3f201900-3a34-11ea-9be2-ba9c129771a1.png">

Can I use this `AppcompatId`?

**Comment by takahirom** [comment]
Thanks! Can you use `AppcompatRId`? Because Android engineers are used to R.

**Comment by rockun1** [comment]
Thank you for your reply! 

> Can you use AppcompatRId?

OK, use `AndroidR*` and `AppcompatR*` .
