### ISSUE TITLE
Add ViewModel test for Staffs

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#361]
## Overview (Required)
The title says everything. 💯 
This issue blocked by https://github.com/DroidKaigi/conference-app-2020/issues/360

## Links
- https://github.com/DroidKaigi/conference-app-2020/blob/8691c73ccfaa7ba626752433d7b97d744a2e679f/feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/AnnouncementViewModel.kt

**Comment by a25max** [comment]
I want to try it.

**Comment by ho2ri2s** [comment]
I did #360 . 
I also want to challenge #361 🙋‍♂️

**Comment by e10dokup** [comment]
@ho2ri2s Thanks! We assigned this issue to you! :bowing_man:
