### ISSUE TITLE
Add white spaces to tab labels

### ISSUE THREAD

**Issue by matsujun** [DroidKaigi/conference-app-2020#376]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add white spaces to follow Figma design.

| Figma | Current App |
--- | ---
| <img width="200" alt="▶_App_-_App" src="https://user-images.githubusercontent.com/10704349/72659026-ac17bc80-39fc-11ea-95f9-b1053f5be0a0.png"> | <img width="200" alt="▶_App_-_App" src="https://user-images.githubusercontent.com/10704349/72659012-622ed680-39fc-11ea-94bb-011a74473509.png"> |

**Comment by kouhon** [comment]
:hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
