### ISSUE TITLE
From the app icon to determine whether to debug or release

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#381]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now it is the same. We can not determine 😅 
![image](https://user-images.githubusercontent.com/1386930/72659810-e2f3cf80-3a08-11ea-8f28-bcf1aba17540.png)

 ## Links	

-

**Comment by orimomo** [comment]
🙋‍♀️

**Comment by satsukies** [comment]
@orimomo Thank you! We assign this issue to you :+1:

**Comment by takahirom** [comment]
Assigned 👍
