### ISSUE TITLE
There is no bottom padding at Timeline Filter

### ISSUE THREAD

**Issue by umechanhika** [DroidKaigi/conference-app-2020#384]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It is necessary 40dp padding between chip and bottom sheet in Timeline Filter.

## Links

- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=11%3A625

## Image
| Figma | App |
|---|---|
| ![image](https://user-images.githubusercontent.com/47149507/72660588-294e2c00-3a13-11ea-9379-34f676c1bcfe.png) | ![screenshot](https://user-images.githubusercontent.com/47149507/72660610-78945c80-3a13-11ea-96a7-17a5ec86054a.png) |

**Comment by takahirom** [comment]
A very easy-to-understand issue!

**Comment by tsumuchan** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned!
