### ISSUE TITLE
Fade out myPlan's emptyView after visible my plan list

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#385]
## Kind (Required)

- Improvement

 ## Overview (Required)

- EmptyView see for a moment in spite of having favorite sessions when specific cases.
    - 1. When opening app and slide to myPlan tab firstly.
    - 2. When moving to session detain and come back to myPlan screen.
- Should set to gone visibility in default value?🐶

 ## Screenshot
<img src="https://user-images.githubusercontent.com/27717556/72660711-89919d80-3a14-11ea-9562-771bb8ac258e.gif" width="300" />

**Comment by b4tchkn** [comment]
🙋‍♂️

**Comment by FujiKinaga** [comment]
@b4tchkn 
Thanks! Assigned! 👍

**Comment by FujiKinaga** [comment]
It seems to be fixed by #421 💯
