### ISSUE TITLE
Expand tap area for speaker session

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#386]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Expand tap area for speaker session
![image](https://user-images.githubusercontent.com/1386930/72661195-cd87a100-3a1a-11ea-935c-a2914917cfbc.png)

 ## Links	

-

**Comment by beta1139** [comment]
🙋‍♀

**Comment by FujiKinaga** [comment]
@beta1139 
Thanks! Assigned 👍
