### ISSUE TITLE
Vanish search menu when screen rotate.

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#387]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Title says it everything🙏

 ## Screenshot
![fps_30](https://user-images.githubusercontent.com/27717556/72661319-bc8b5f80-3a1b-11ea-8c16-a5580622c86e.gif)

**Comment by a25max** [comment]
I want to try it.

**Comment by roana0229** [comment]
Of course, assigned 👍

**Comment by FujiKinaga** [comment]
@a25max 
Hi.
This problem seems to be fixed by #404 😭
It's so sorry, but we are looking forward to your contribution in next issue...!

**Comment by a25max** [comment]
@FujiKinaga I see. I'll try another issue.
