### ISSUE TITLE
Content area must be scrollable and viewable in preparation for screen rotation

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#388]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Sometimes, we can't view screens because of non-scrollable and non-margin.
- Please try look into various screen layout for refactoring!

 ## Screenshot	
For example, just like this.

![device-2020-01-18-180302](https://user-images.githubusercontent.com/27717556/72661404-ce213700-3a1c-11ea-95f0-2b12a714b7bb.png)

**Comment by 5hyn3** [comment]
🙋‍♂️

**Comment by roana0229** [comment]
Assigned 👍
