### ISSUE TITLE
Apply speaker item's design in session detail screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#390]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please correct it as designed.
    - String localizing
    - User icon sizing
    - Speaker name sizing
    - Should more intuitive tap feedback like speaker layout of day's session
    - etc. Welcome your improvement ideas!

 ## Links	
Current | Ideal
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72661494-fe1d0a00-3a1d-11ea-956b-69a1e1131a2c.png" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72661495-feb5a080-3a1d-11ea-8733-6a2550e0f9f8.png" width="300" />

**Comment by sasakitomohiro** [comment]
🙋‍♀️

**Comment by roana0229** [comment]
Assigned 👍
