### ISSUE TITLE
Dynamically expand the tappable area when collapsed session filter

### ISSUE THREAD

**Issue by rwadada** [DroidKaigi/conference-app-2020#393]
## Kind (Required)
- Improvement

 ## Overview (Required)

- Move the line down as you scroll to expand the tappable area.
<img src="https://user-images.githubusercontent.com/1386930/72659193-4b3db380-39ff-11ea-862f-d9318e196233.png" width="400" />

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/pull/367#issuecomment-575868989
- [About MotionLayout](https://developer.android.com/reference/android/support/constraint/motion/MotionLayout)

**Comment by takahirom** [comment]
For reference, you do not need to change the tap area. I just want to move the line as the BottomSheet scrolls.
I think MotionLayout can be used for this.

**Comment by kazaman97** [comment]
🙋‍♀️

**Comment by roana0229** [comment]
Assigned 👍

**Comment by kazaman97** [comment]
I'm sorry.
I can't understand the meaning of this problem so much.
I want you to tell me a problem in detail.🙇🏻‍♂️

**Comment by jmatsu** [comment]
@takahirom cc: @rwadada 
Could you please provide more information like the current *unexpected* behavior and the *expected* state?

**Comment by rwadada** [comment]
@kazaman97 
Sorry for lack of information 🙇 

At present, when you open the Filter screen (close the Session screen) when GestureNavigation is enabled , there is a blank space at the bottom where there is no response.

For this issue, if GestureNavigation is enabled, I think it is necessary to change the position of the line "divider" on the session screen (fragment_bottom_sheet_sessions) to 48dp below according to scrolling.

MotionLayout is suggested as a solution, but I think you can use any solution you like without using it.

@takahirom 
Please supplement as it may be wrong 🙏

**Comment by kazaman97** [comment]
@rmakiyama @jmatsu
Thank you for telling me🙇🏻‍♂️
I understand the meaning of the issue and work on the issue!

**Comment by jmatsu** [comment]
Thank you all! We are looking forward to your contribution.

**Comment by takahirom** [comment]
@rwadada Thank you 🙏
