### ISSUE TITLE
Myplan's empty session view is visible when only speakerless sessions are favorited

### ISSUE THREAD

**Issue by imsaku** [DroidKaigi/conference-app-2020#394]
## Kind (Required)
- Improvement

 ## Overview (Required)
Myplan's empty session view is visible when favorite sessions are only speakerless events("Welcome Talk", "Lunch", "Party") 
I think it should be invisible in this case.

![empty-session-visible](https://user-images.githubusercontent.com/58973616/72662466-dc764f80-3a2a-11ea-94cb-c84758d5ed55.gif)

**Comment by roana0229** [comment]
Thanks for your report. It makes sense 👍

**Comment by akihito-okada** [comment]
🙋‍♂️

**Comment by roana0229** [comment]
Assigned 👍
