### ISSUE TITLE
Hardly see the BottomSheet expand icon when app running on dark theme

### ISSUE THREAD

**Issue by k3nsuk3** [DroidKaigi/conference-app-2020#396]
## Kind (Required)

- Improvement

 ## Overview (Required)

- BottomSheet expand icon color is always dark, even if app running on dark theme

 ## Links	

-

## Screenshot

Pixel 3a Emulator, Android 9, API 28

|Dark|Light|
|:---:|:---:|
|![dark-expand-icon](https://user-images.githubusercontent.com/4849408/72662475-f9ab1e00-3a2a-11ea-94dd-1e9c12020a21.png)|![light-expand-icon](https://user-images.githubusercontent.com/4849408/72662480-00399580-3a2b-11ea-8581-beb9962d640c.png)|

**Comment by roana0229** [comment]
Thanks for your report !

**Comment by k3nsuk3** [comment]
May I fix it?

**Comment by roana0229** [comment]
Of course, assigned 👍
