### ISSUE TITLE
If filter hits on MyPlan page, filter button is shown

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2020#397]
**Overview (Required)**
- on MyPlan page set filter and some favorite session hits then filter button appear. (and session list too)

**Steps To Reproduce**

1. Add some sessions to favorite
2. go to MyPlan page
3. show filters and set some filter to be hit favorite session
4. then it is appeared session list and filter button

**Expected behavior**
same as Day1/Day2 page.
(on Day1/Day2 page, this issue dose not occur)

**Screenshots**

![myplans_filter_bug](https://user-images.githubusercontent.com/7608725/72663027-3d088b00-3a31-11ea-8378-6ce16910b6ac.gif)

**Env:**
 - Device: Nexus6P
 - OS: 8.1.1 (Android 10 too)
 - master

**Comment by t-kashima** [comment]
🙋‍♂️

**Comment by FujiKinaga** [comment]
@t-kashima 
Thanks! 
Assigned!👍
