### ISSUE TITLE
Implement about droidkaigi screen without design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#40]
## Overview (Required)
Title says everything.

**Comment by TaigaNatto** [comment]
🙋‍♂️
i want to try this issue 

What is the goal specifically on this issue ?

**Comment by takahirom** [comment]
Thanks for your interest in this issue. 🗺
Not ready to address this issue. The design is likely to change a little from last year, so it seems unlikely that we can do so much.
You can assign and keep this issue, or work on other issues.

**Comment by TaigaNatto** [comment]
Thanks for reply

ok,I'll try other isuue.
May I retry this issue when ready on design ?

**Comment by takahirom** [comment]
You can assign multiple issues. How about it?

**Comment by takahirom** [comment]
Now we can access the Design!!

**Comment by TaigaNatto** [comment]
@takahirom 
really!? i want to try this issue !

**Comment by FujiKinaga** [comment]
@TaigaNatto 
Of course!!
Assigned👍

**Comment by TaigaNatto** [comment]
How much to implement on this issue ?

Should I wait for #41  to complete?

**Comment by takahirom** [comment]
Thanks! I was thinking about doing this issue first.🙏

**Comment by TaigaNatto** [comment]
Thank you ! I try it early !

**Comment by takahirom** [comment]
@TaigaNatto Please let me know if you have any questions 🙏

**Comment by TaigaNatto** [comment]
@takahirom 
Thank you.
It feels good for this issue.

I just have question.
- I'm trying to implement RecyclerView, can I just look at the existing implementation?
- How much should I implement?

**Comment by takahirom** [comment]
@TaigaNatto 

> I'm trying to implement RecyclerView, can I just look at the existing implementation?

Sorry.  I don't understand. "look at the existing implementation" means using existing Groupie Item?? I think It is better to make it. 🙏 

> How much should I implement?

For now,  All you need to do is create an item for Groupie and just show the string. 
It's okay to implement the design, but I'm already running out of time so I want to get it early. 🙇

**Comment by TaigaNatto** [comment]
@takahirom 
I just did it ! Sorry for being late.

I have some questions.
- Should Top Image prepare image data for each dpi?
- Is there an implementation to get the version code of the app?

**Comment by takahirom** [comment]
> Should Top Image prepare image data for each dpi?

Now you can use empty image 👍 

> Is there an implementation to get the version code of the app?

It is ok to empty for now 👍
