### ISSUE TITLE
Hardly see the MY PLAN's BottomSheet expand icon when app running on dark theme

### ISSUE THREAD

**Issue by k3nsuk3** [DroidKaigi/conference-app-2020#406]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Related to #396 , I didn't notice that bottom sheet layout for DAY1/DAY2 and MY PLAN are separated, sorry... 😢

 ## Links	

-

## Screenshots

Pixel 3a emulator, Android 9, API 28

|Dark|Light|
|:---:|:---:|
|![current-dark](https://user-images.githubusercontent.com/4849408/72665038-1ace3780-3a48-11ea-80e8-ede9a1e8a6ee.png)|![current-light](https://user-images.githubusercontent.com/4849408/72665040-215caf00-3a48-11ea-8bba-29b9feec3395.png)|

**Comment by k3nsuk3** [comment]
I want to fix it, too! 🙋🏻‍♂️

**Comment by roana0229** [comment]
Awesome! I didn't notice too.
Assigned 👍
