### ISSUE TITLE
Speakerless sessions are always shown when some filter selected

### ISSUE THREAD

**Issue by umechanhika** [DroidKaigi/conference-app-2020#407]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

Speakerless sessions are always shown when some filter selected.
I think it is better not to be displayed.
What do you think about this?

 ## Example
Select "Hardware" filter.
![screenshot1](https://user-images.githubusercontent.com/47149507/72665336-b9f42e80-3a4a-11ea-9fed-d0cf24d17549.png)

Speakerless sessions are shown.
![screenshot2](https://user-images.githubusercontent.com/47149507/72665339-caa4a480-3a4a-11ea-8f14-582ea10c265c.png)

**Comment by takahirom** [comment]
I think it would be helpful if lunch etc. were displayed as it was relevant to everyone.
Please let me know if you have any opinions.

**Comment by umechanhika** [comment]
These sessions have no relationship with selected filter, so I thought it is better not to be displayed.
But I saw your opinion, I agreed it.
These are helpful understanding timeline.

Thank you your opinion!
