### ISSUE TITLE
Use onViewCreated instead of onActivityCreated for AboutFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#415]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We use onViewCreated for binding view data

 ## Links	

- https://android-review.googlesource.com/c/platform/frameworks/support/+/1189651

**Comment by akihito-okada** [comment]
🙋

**Comment by roana0229** [comment]
Assigned 👍

**Comment by akihito-okada** [comment]
@roana0229 @takahirom 
I'm sorry for the delay. It seems that this issue is fixed. Please confirm if you have no problem and close.

**Comment by roana0229** [comment]
👀  https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt

Thank you, I confirmed that it was already solved. 👍
