### ISSUE TITLE
Fix sessions are displayed after changing filters

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#418]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Sessions is hide when collapsed.
- But sessions are displayed after changing filters.

<img src=https://user-images.githubusercontent.com/6636072/72669270-f9367580-3a72-11ea-9ca9-cc190b779a8d.gif  width=50%>

<img src=https://user-images.githubusercontent.com/6636072/72669305-8679ca00-3a73-11ea-817c-7452c9e2354e.png  width=50%>

 ## Links	

-

**Comment by umechanhika** [comment]
🙋

**Comment by yurihondo** [comment]
Thanks!! Assigned:D
