### ISSUE TITLE
Use binding adapter at session time summary

### ISSUE THREAD

**Issue by roana0229** [DroidKaigi/conference-app-2020#419]
## Kind (Required)

- Improvement

 ## Overview (Required)

- see `FIXME` comment
- https://github.com/DroidKaigi/conference-app-2020/blob/600dc20edce5ac1e900fb1fe2bf1252ce5622800/feature/session/src/main/res/layout/item_speaker_session.xml#L88
- https://github.com/DroidKaigi/conference-app-2020/blob/600dc20edce5ac1e900fb1fe2bf1252ce5622800/feature/session/src/main/res/layout/fragment_session_detail.xml#L105
- Create `timeSummary` on binding adapter and change `FIXME` on xml.

 ## Links	

-

**Comment by umechanhika** [comment]
🙋

**Comment by FujiKinaga** [comment]
@umechanhika 
Thanks! Assigned! 👍

**Comment by umechanhika** [comment]
I faced a problem.

`com.soywiz.klock.TimezoneOffset` class is written using kotlin inline class. This class wrap double type value.
`SpeechSession#timeSummary(Lang, TimezoneOffset)` method convert to `SpeechSession#timeSummary(Lang, double)` when kotlin converted to java.
And also method name is changed `timeSummary` to `timeSummary-PjeVyQw`.
So it occurs compile error.
```
cannot find method timeSummary(io.github.droidkaigi.confsched2020.model.Lang, com.soywiz.klock.TimezoneOffset) in class io.github.droidkaigi.confsched2020.model.SpeechSession
```

I found stackoverflow but it is not still resolved.
https://stackoverflow.com/questions/54139949/how-to-integrate-kotlin-inline-class-with-android-data-binding

Do you have any ideas?
I want to help me.

**Comment by k3nsuk3** [comment]
@umechanhika 

You may have encountered this: https://stackoverflow.com/a/54240323
I'm not familiar about it. I implemented below method into Session class and could be able to compile.

```kotlin
fun timeSummary(lang: Lang, timezoneOffset: Double) = timeSummary(lang, TimezoneOffset(timezoneOffset))

fun timeSummary(lang: Lang, timezoneOffset: TimezoneOffset) = buildString {
...
```

But I don't want to write it because I feel it's redundant.
I want to know how to solve this in right way. 🤔

**Comment by umechanhika** [comment]
@k3nsuk3 

Thank you for your proposed!
I tried it and confirmed that it works properly.

>But I don't want to write it because I feel it's redundant.
>I want to know how to solve this in right way. 🤔

I think so too.
At the moment there is no other way, so I would like to proceed with the implementation your proposed.
