### ISSUE TITLE
ProgressBar isn't shown in announcement page when this page opened for the first time

### ISSUE THREAD

**Issue by umechanhika** [DroidKaigi/conference-app-2020#423]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It shows empty view "No announcement".
- I think it is prefer showing ProgressBar when this page opened for the first time.

 ## Gif
![record](https://user-images.githubusercontent.com/47149507/72675861-e3a26980-3acd-11ea-8078-1a88dccc3cc8.gif)

**Comment by tatsuya-okayama** [comment]
I want to try it !! 🙋‍♂

**Comment by FujiKinaga** [comment]
@tatsuya-okayama 
Thanks!! Assigned 👍
