### ISSUE TITLE
Sometimes, when returning from session details, the scroll position of the session list is reset

### ISSUE THREAD

**Issue by kkt-yu** [DroidKaigi/conference-app-2020#424]
**Overview (Required)**
- Sometimes, when returning from session details, the scroll position of the session list is reset

**Steps To Reproduce**

1. Go to session details.
2. Return session list.
3. Sometimes,reload and reset position of session list.

**Expected behavior**
Don't reload and reset position.

**Screenshots**
N/A

**Env:**
 - Device: Xperia 10
 - OS: 9.0
 - master

**Comment by gen0083** [comment]
I cannot know the cause yet, but I found a way to reproduce it.

1. scroll and open session detail.
2. repeat scroll up/down some times. (it's enough to scroll BottomAppBar)
3. back session list then reload and move to top of session list.

![reproduce_step 2020-01-19 19_38_14](https://user-images.githubusercontent.com/7608725/72679535-76093400-3af3-11ea-8dba-2d45071807ba.gif)

**Comment by kkt-yu** [comment]
Maybe if you open it for more than 5 seconds ,it reproduce
Operation does not matter.

**Comment by numa08** [comment]
✋ 

Can I try this ?

**Comment by takahirom** [comment]
Can you do it? Thanks!!!!🙏
