### ISSUE TITLE
When not adaptive icon, The icon is too big

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#425]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We can use image from figma assets
![image](https://user-images.githubusercontent.com/1386930/72676138-2f0a4700-3ad1-11ea-95f4-cca03b83c595.png)

 ## Links	

-

**Comment by yiwaisako** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
