### ISSUE TITLE
Implement floor map screen without design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#43]
## Overview (Required)
Title says everything.

**Comment by eyedol** [comment]
Can you assign this to me? Since it lacks design should I replicate what's done in `conference-app-2019` ?

**Comment by takahirom** [comment]
Thanks for your interest in this issue. 🗺 
Not ready to address this issue. The design is likely to change a little from last year, so it seems unlikely that we can do so much.
You can assign and keep this issue, or work on other issues.
For now, the current schedule is a screen with a single map image that can be enlarged or reduced. Ideally, I want the screen to look like a Google Map.
It is okay to once implement and merge in such a form and change the design later 👍

**Comment by eyedol** [comment]
Oh okay. I'll like to assign it to myself so when the design is ready I can work on it. Right now, I can't assign the issue to myself. Also, I'll pick another issue to work on in the meantime 🤞

**Comment by takahirom** [comment]
Thanks! I assigned! Thanks as always 🎉

**Comment by takahirom** [comment]
@eyedol The design is uploaded 😄

**Comment by eyedol** [comment]
Great, 👍  it's the one uploaded to Figma right?

**Comment by takahirom** [comment]
You can check this 😄 You can download the map image from it. If you login figma. 
Note: The image is not fixed yet
https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=847%3A104

**Comment by eyedol** [comment]
Will there be different floors? Like will it need to be paginated?

**Comment by takahirom** [comment]
There is only one floor. But the floor is wide. 👀
