### ISSUE TITLE
Change specific chip's color in session detail screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#436]
## Kind (Required)

- Improvement

 ## Overview (Required)

- To check session's better important information, some chips should be changed color from the other chips color.
    -Please change color about `language` and `for beginner` chips.

 ## Image	
<img width="341" alt="スクリーンショット 2020-01-19 19 32 33" src="https://user-images.githubusercontent.com/27717556/72679443-78b75980-3af2-11ea-83c1-a360c30f12c3.png">

**Comment by ttanaka330** [comment]
🙋‍♂

**Comment by FujiKinaga** [comment]
@ttanaka330 
Thanks! Assigned 👍

**Comment by ttanaka330** [comment]
I have a question.
How do I check `for beginner`?

I looked at the data, but it doesn't seem to get the levels from the timetable...

**Comment by ttanaka330** [comment]
To solve this issues, you must first specify `for beginner` in the session details.

The steps are as follows:
1. Perform a session table migration (add `levels` or `isForBeginneer` column).
2. Get `levels` from the timetable API.
3. Save the `levels` in the session table.
4. Display the "for Beginner" chip in SessionDetail.

After this, the chip is colored.
I want to do this too, is that OK?

The worrisome point is that the level filter on the timeline screen is not working (not implemented).
And the same value is set for all timetable API levels.
```
"levels": [
  "BEGINNER",
  "INTERMEDIATE",
  "ADVANCED"
]
```
