### ISSUE TITLE
Search sessions or speakers by your voice in search screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#438]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Title says everything!

 ## Links	
- Figma
    - https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=842%3A907

## Image
<img width="228" alt="スクリーンショット 2020-01-19 19 40 42" src="https://user-images.githubusercontent.com/27717556/72679556-bd8fc000-3af3-11ea-9694-21d835d3aad2.png">

**Comment by sobaya-0141** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Assigned📢

**Comment by sobaya-0141** [comment]
I,m sorry
I can't come up with a solution

reference:https://developer.android.com/guide/topics/search/search-dialog.html#VoiceSearch

I tried the following
- Add res/xml/searchable.xml
`
android:voiceSearchMode="showVoiceSearchButton|launchRecognizer"
`
- AndroidManifest.xml
`            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable" />`

but, the mic icon did not appear.

Sorry, let me give up

**Comment by jmatsu** [comment]
@sobaya-0141 
No worries. Great job.

What device did you use by the way? I have experienced a similar issue on several devices that haven't installed Google App.

**Comment by jmatsu** [comment]
Let me remove you from assignees for now.

**Comment by sobaya-0141** [comment]
> What device did you use by the way? I have experienced a similar issue on several devices that haven't installed Google App.

The terminals used are Pixel3a and Huawei nova lite2.
In both cases, the Google app will be installed.

**Comment by imsaku** [comment]
Can I try it?

**Comment by roana0229** [comment]
Of course, assigned 👍
