### ISSUE TITLE
Apply navigation view design

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#439]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We can change padding between icon and title.
- We can change some icons.

 ## Screenshot	
Currently | Design
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72679732-625ecd00-3af5-11ea-8393-123c64087035.png" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72679733-62f76380-3af5-11ea-9f1d-5c3e7a1526d1.png" width="300" />

**Comment by nano-nano** [comment]
I'll try to do this issue.✋
Where are icon's resource files?
And is layout spec below link?
https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=21%3A543

このissueをやりたいのですが、新しいアイコンのリソースはどこにあるでしょうか？
それと、paddingの指定があるレイアウトの仕様は上記リンクのもので合ってますでしょうか？

**Comment by takahirom** [comment]
Thanks! 
If you log in, I think you can download images 👀 

> And is layout spec below link?

Yes
