### ISSUE TITLE
Apply floor map screen design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#44]
## Overview (Required)
- Title says everything.
- This issue blocked by #43

**Comment by phicdy** [comment]
@takahirom 
Hi, I'm interested in this issue. I checked the figma and have some question about this issue. 

- Is What should I do just set map svg in the center of the screen ? 
- What do you mean the location icon ? Can I ignore it ?

![Screenshot from 2020-01-19 20-03-22](https://user-images.githubusercontent.com/1650277/72679861-cd5cd380-3af6-11ea-86b3-f8b4505a8b10.png)

- I think we can delete [FloorMap](https://github.com/DroidKaigi/conference-app-2020/blob/master/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/FloorMap.kt). It looks to be for the floor last year. Can I delete it ?

**Comment by phicdy** [comment]
Oh sorry, I missed #43... Please ignore my comment.

**Comment by takahirom** [comment]
Sorry 🙇
