### ISSUE TITLE
Change to use vertical chain style and change scrollable in my plan's empty view

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#441]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This empty view should locate center position with a little top margin.
- We can't view screen because of non-scrollable😭

 ## Screenshot
![device-2020-01-18-180302](https://user-images.githubusercontent.com/27717556/72661404-ce213700-3a1c-11ea-95f0-2b12a714b7bb.png)
<img src="https://user-images.githubusercontent.com/27717556/72679945-cc787180-3af7-11ea-86db-afb259292f45.png" width="300" />

## Links
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=11%3A432

**Comment by shinya-takano** [comment]
🙋‍♂ OK?

**Comment by roana0229** [comment]
Of course, assigned 👍

**Comment by shinya-takano** [comment]
already fixed this issue. please close this issue.

**Comment by FujiKinaga** [comment]
@shinya-takano 
Thanks for your remind.
I've closed this PR ✋
