### ISSUE TITLE
Apply session item design in timeline screens

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#442]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please remove button of session's feedback.
- Please add session time left of hall name.
- etc...

 ## Links	

- Figma
    - https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=4%3A2

## Screenshot
Currently | Design
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72680078-09913380-3af9-11ea-8404-afbb56e74711.png" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72680077-08f89d00-3af9-11ea-98b1-feedf15fefd6.png" width="300" />

**Comment by a25max** [comment]
I want to try it.

**Comment by matsujun** [comment]
Assigned ! 🚀
