### ISSUE TITLE
Remove button of session's feedback in session detail screen

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#443]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Title says everything😄

## Links
- Related to #429 

 ## Screenshot	
<img src=https://user-images.githubusercontent.com/27717556/72680113-82908b00-3af9-11ea-8e4e-602a513a8b17.png width=300 />

**Comment by hanadaUG** [comment]
🙋‍♂

**Comment by FujiKinaga** [comment]
@hanadaUG 
Thanks! Assigned👍
