### ISSUE TITLE
Should add few margin to a end of announcement item 

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#444]
## Kind (Required)
Improvement

 ## Overview (Required)
I think that it should add few margin to a end of announcement item.
(Especially when "Read more" is displayed.)

 <img src="https://user-images.githubusercontent.com/33515193/72680351-427ed780-3afc-11ea-8b2d-3a148b81373f.png" width="320px">

 ## Links

**Comment by ujikawa** [comment]
🙋‍♂

**Comment by yurihondo** [comment]
Thanks,  Assigned!!
