### ISSUE TITLE
Realize material animation like Motion app

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#445]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Animation with displaying list by [List > Stagger](https://github.com/android/animation-samples/tree/master/Motion/app/src/main/java/com/example/android/motion/demo/stagger),
    - ex. contributors or staffs screens. 
<img src=https://raw.githubusercontent.com/android/animation-samples/master/Motion/screenshots/stagger.gif width=300 />

- Animation with transition by [Navigation > Fade through](https://github.com/android/animation-samples/tree/master/Motion/app/src/main/java/com/example/android/motion/demo/navfadethrough),
    - ex. session list -> session detail. 
<img src=https://raw.githubusercontent.com/android/animation-samples/master/Motion/screenshots/navigationfadethrough.gif width=300 />

 ## Links	

- https://github.com/android/animation-samples/tree/master/Motion

**Comment by koji-1009** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned🙏

**Comment by koji-1009** [comment]
🤔 

| | before | after |
| --- | --- | --- |
| congributor(stagger) | ![before_contributor](https://user-images.githubusercontent.com/17231507/73074168-565f7a80-3efc-11ea-8c32-dcc22eee3a78.gif) | ![after_contributor](https://user-images.githubusercontent.com/17231507/73074167-565f7a80-3efc-11ea-93ea-bca0846ab282.gif) |
| staff(stagger) | ![before_staff](https://user-images.githubusercontent.com/17231507/73074214-72fbb280-3efc-11ea-8736-4d2fa0ec4a29.gif) | ![after_staff](https://user-images.githubusercontent.com/17231507/73074212-72fbb280-3efc-11ea-94da-e9f4f066ddf4.gif) |
| fade through | ![before_fade_through](https://user-images.githubusercontent.com/17231507/73074220-7727d000-3efc-11ea-8616-7ac366626277.gif) | ![after_fade_through](https://user-images.githubusercontent.com/17231507/73082507-f32a1400-3f0c-11ea-9b5a-efe02d53f281.gif) |

**Comment by koji-1009** [comment]
👨‍🚀 

| | before | after |
| --- | --- | --- |
| fade transition | ![before_fade](https://user-images.githubusercontent.com/17231507/73116441-c6601600-3f79-11ea-845b-5620cf5054fa.gif) | ![after_fade](https://user-images.githubusercontent.com/17231507/73116442-c6f8ac80-3f79-11ea-9f35-139da59b3cd1.gif) |
