### ISSUE TITLE
Change filter state label in each timeline screens

### ISSUE THREAD

**Issue by FujiKinaga** [DroidKaigi/conference-app-2020#446]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Change the label depending on whether you are filtering.

 ## Screenshot	
Not filtered | Filtering
:--: | :--:
<img src="https://user-images.githubusercontent.com/27717556/72680778-16b22080-3b01-11ea-9d4f-7247b8ee5a1c.png" width="300" /> | <img src="https://user-images.githubusercontent.com/27717556/72680779-16b22080-3b01-11ea-8a3e-6c85c61f9f86.png" width="300" />

**Comment by a25max** [comment]
I want to try it.

**Comment by matsujun** [comment]
Thanks!
Assigned 👍
