### ISSUE TITLE
Use targetSdkVersion 29 and compileSdkVersion 29

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#454]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is no reason why it is currently API Level 28, and I just forgot it. 😄 

 ## Links	

-

**Comment by tatsuya-okayama** [comment]
I want to try it !! 🙋‍♂

**Comment by roana0229** [comment]
Of course, assigned 👍
