### ISSUE TITLE
Travis CI fail (release build fail)

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#457]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This script run on CI
- .travis/android/script.bash

```
* What went wrong:
Execution failed for task ':android-base:mergeReleaseClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Entry name 'io/github/droidkaigi/confsched2020/util/DaggerFragment_MembersInjector.class' collided
```

 ## Links	

-

**Comment by takahirom** [comment]
Probably we should revert this 😭 
https://github.com/DroidKaigi/conference-app-2020/pull/414

**Comment by takahirom** [comment]
https://github.com/google/dagger/issues/814#issuecomment-316016739

**Comment by takahirom** [comment]
It seems a little difficult to fix, so I want to revert for the time being.

**Comment by chibatching** [comment]
oh... 😢
