### ISSUE TITLE
When the navigation drawer is displayed, the status bar suddenly goes dark

### ISSUE THREAD

**Issue by ushi3** [DroidKaigi/conference-app-2020#463]
**Overview (Required)**

In MainSessionsFragment, pull out Drawer manually. Will see the status bar suddenly goes dark.

**Steps To Reproduce**

1. Stay MainSessionsFragment
2. Pull out Drawer
3. Status bar suddenly goes overlaid dark

**Expected behavior**
If it's clear

**Screenshots**

![ezgif-3-6df24ba14f95](https://user-images.githubusercontent.com/1962232/72704870-3eef5d00-3b9d-11ea-98c7-0a444c5a0e9e.gif)

**Env:**
 - Device: Pixel 3a XL
 - OS: Android 10
 - App Version or the branch: 1.0.5 (Install from DeployGate)

**Additional context**
Why, only happen in MainSessionsFragment?

**Comment by ham-burger** [comment]
@ushi3 
I think, time text become gone if Status bar would be clear when Drawer opened.
Is that OK?

**Comment by ham-burger** [comment]
![Screenshot_20200120-201515](https://user-images.githubusercontent.com/25279469/72722513-db2b5b00-3bc1-11ea-826e-ce481f33f3f9.png)

**Comment by ushi3** [comment]
> @ushi3
> I think, time text become gone if Status bar would be clear when Drawer opened.
> Is that OK?

I see.

I would choice, dark overlay status bar.
However, for this project we must respect the opinions of main contributors and designers.
Sorry, I have no right about this.

@takahirom @chihokotaro
