### ISSUE TITLE
Dark theme does not properly saved

### ISSUE THREAD

**Issue by ytRino** [DroidKaigi/conference-app-2020#465]
**Overview (Required)**
- Dark theme setting is not saved so theme is set on every launch.

**Steps To Reproduce**

1. Launch app with system dark setting is off.
2. Open setting and set to dark.
3. Dismiss app from history.
4. Launch app again. App is light theme.

**Expected behavior**
Dark theme is set.

**Env:**
 - Device: Pixel3 XL
 - OS: 10
 - App Version or the branch: master

**Additional context**

**Comment by takahirom** [comment]
Thanks! I forgot this issue 😄 
https://github.com/DroidKaigi/conference-app-2020/pull/95#issuecomment-573287085
![relaunch](https://user-images.githubusercontent.com/1386930/72199862-897a2680-3485-11ea-859e-44adced9bc42.gif)

**Comment by ytRino** [comment]
@takahirom 👍 Then if you interested  in #466 , I will do it along with this.

**Comment by ytRino** [comment]
This is fixed in above PR. Thanks:+1:
