### ISSUE TITLE
Behave consistent around dark theme

### ISSUE THREAD

**Issue by ytRino** [DroidKaigi/conference-app-2020#466]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- Currently app is themed with system settings (related: #465) on launch. It seems to behave like `MODE_NIGHT_FOLLOW_SYSTEM` so switching system dark settings updates switch in app as well. 
- However, once check/uncheck the dark theme switch, it behaves as MODE_NIGHT_YES/MODE_NIGHT_NO. At that time, switching system dark settings no longer updates switch in app.
- It is good to add `MODE_NIGHT_FOLLOW_SYSTEM` so that user can choose fixed(dark/light) or system dependent. 

How about it?

 ## Links	
- https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94

**Comment by takahirom** [comment]
It's a bit confusing to the user, so it may not be necessary at the time of release. However, once you add that function, you can clarify the dark mode movement, so it may be clear what to do.

**Comment by takahirom** [comment]
Ideally, if you change from the settings of DroidKaigi, you should give priority to the settings of DroidKaigi, and until you change it, it is better to give priority to the settings of the system. 👀

**Comment by takahirom** [comment]
@ytRino Please tell your opinion. 🙏

**Comment by ytRino** [comment]
yes, I intended what you said maybe. I'm planing that of Gmail app.
![image](https://user-images.githubusercontent.com/1487505/72769565-7b26ca00-3c3e-11ea-976a-38c25eeb10cc.png)
Both dark/light is app overridables and default is system dependent.
If we implement #465 without this, we can no longer have system dependent once user switched it in app.
What user will see in preferences screen in app (after #465 )

|    | without this | with this
---|---------|----
launch (not selected any) | "dark" or "light" <br>(behavior is system default)| "system default"
launch with "system default" | (not available) | "system default"
launch with "dark" | "dark" | "dark"
launch with "light" | "light" | "light"

**Comment by takahirom** [comment]
LGTM! 👍

**Comment by ytRino** [comment]
Thanks! I'll continue working on this.
