### ISSUE TITLE
Chip text color for dark theme

### ISSUE THREAD

**Issue by ytRino** [DroidKaigi/conference-app-2020#468]
## Kind (Required)
- Improvement

 ## Overview (Required)
- It looks text color for selected filter chips are little hard to read. Same color with light theme looks fine for me.

 
![image](https://user-images.githubusercontent.com/1487505/72714660-6e5c9480-3bb2-11ea-890f-fe453eb0fd3c.png)

**Comment by dongheeleeme** [comment]
Can i was assigned this ticket? :)

**Comment by yurihondo** [comment]
Yes, of course! Thanks!!
Assigned 🙏

**Comment by devKeeey** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
@dongheeleeme Sorry I give this issue @devKeeey
