### ISSUE TITLE
Crash when tapping multiple Items at the same time on Sessoion screen

### ISSUE THREAD

**Issue by rwadada** [DroidKaigi/conference-app-2020#472]
**Overview (Required)**
- Crash when tapping multiple Items at the same time on Sessoion screen

**Steps To Reproduce**

1. Open Session screen.
2. Tap multiple session items on the same time.
3. Release multiple session items on the same time.
4. Crash!

**Expected behavior**
Transition to SessionDetail screen of either Item and do not crash

**Screenshots**
<img src="https://pbs.twimg.com/media/EOoAXuAU8AE8TrO?format=jpg&name=4096x4096" width="300">
<img src="https://pbs.twimg.com/media/EOoAYCeUUAAMpXf?format=jpg&name=4096x4096" width="300">

**Env:**
 - Device: Pixel3a
 - OS: Android 10.0
 - App Version or the branch : master

**Comment by umechanhika** [comment]
🙋
