### ISSUE TITLE
Fading animation is delayed when bottom sheet expanded.

### ISSUE THREAD

**Issue by umechanhika** [DroidKaigi/conference-app-2020#484]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is a difference in the way of delay depending on how to operate.
- When you tapped the `expand_less` icon to expand bottom sheet, recyclerView appears dimmed and it appears correct after a few seconds.
- When you swiped the bottom sheet header to expand bottom sheet, recyclerView doesn't appear and it appears after a few seconds.

 ## Gif
![output](https://user-images.githubusercontent.com/47149507/72740846-daa6ba80-3be9-11ea-835a-962c6d6ec5df.gif)

**Comment by koji-1009** [comment]
Hi!
Maybe, this issue is closed by #762.
