### ISSUE TITLE
iOS App session detail

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#488]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- To see session's detail information.
- Can be transitioned from session list view.

 ## Links	
- [Design - Session](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=20%3A18)
- [Design - Session(Enabled)](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=21%3A289)

**Comment by 417-72KI** [comment]
I will try this✋

**Comment by ry-itto** [comment]
@417-72KI 
Thanks! assigned 👍

**Comment by 417-72KI** [comment]
Since the volume is likely to be large, I once made PR up to this point.

**Comment by ry-itto** [comment]
OK. I will see this PR tonight.
