### ISSUE TITLE
iOS App sidebar

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#489]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- Create a sidebar that can move to other view.

 ## Links	
- [Design](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=21%3A543)
- [Navigation Drawer](https://material.io/components/navigation-drawer/)
  - ~[iOS](https://material.io/develop/ios/components/navigation-drawer/)~
    - ~[Example](https://github.com/Luis1Adrian/MaterialDesign/blob/722399ddce71f214211651d01bdbf344f9c9829c/components/NavigationDrawer/examples/BottomDrawerWithHeaderExample.swift)~
- [Material](https://github.com/CosmicMind/Material)

**Comment by ry-itto** [comment]
I will try this ✋

**Comment by takahirom** [comment]
Thanks!Assigned🙏
