### ISSUE TITLE
iOS App filter view

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#490]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- Create filter view that can filter sessions.

 ## Links	
- [Design](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=11%3A625)
- ~[Chips](https://material.io/components/chips/)~
  - ~[iOS](https://material.io/develop/ios/components/chips/)~
- Please try to use CosmicMind/Material's Chips
  - [Sample](https://github.com/CosmicMind/Samples/tree/development/Projects/Programmatic/ChipBarController)

**Comment by ry-itto** [comment]
I will try this 🤚

**Comment by takahirom** [comment]
Thanks!  Assigned🙏
