### ISSUE TITLE
iOS App contributor view

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#493]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- A view that shows contributors 

 ## Links
- [Design](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=22%3A402)

**Comment by woxtu** [comment]
✋

**Comment by ry-itto** [comment]
Thanks! Assigned 👍
