### ISSUE TITLE
iOS App sponsor view

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#494]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- A view that shows sponsors.

 ## Links	
- [Design](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=22%3A507)

**Comment by yaslab** [comment]
🙋‍♂️ I will try this! I'm interested in Material Components for iOS.

**Comment by satsukies** [comment]
@yaslab Thanks! We assign this issue to you!
