### ISSUE TITLE
iOS App about DroidKaigi view

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#495]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- A view that shows some links and some informations.

 ## Links	

- [Design](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=842%3A1376)

**Comment by myihsan** [comment]
🙋‍♂️I want to try it!
Is there any data I need to get from the remote API?

**Comment by ry-itto** [comment]
@myihsan Thanks!
I think this view doesn't need any data to get from remote API.
Assigned 👍
