### ISSUE TITLE
Home button is difficult to see in dark Theme.

### ISSUE THREAD

**Issue by kkt-yu** [DroidKaigi/conference-app-2020#498]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  Home button is difficult to see in dark Theme.  
- For example, change to white

## Screenshot
<image src="https://user-images.githubusercontent.com/41291352/72772919-baf2af00-3c48-11ea-9c33-89e7af50dadf.jpg" width="300px">

**Comment by KeithYokoma** [comment]
@kkt-yu Thank you for reporting the issue 🎉 

By the way, could you put a screenshot here so that everyone can have an idea where the issue exists?

**Comment by S-Shimotori** [comment]
Thank you for your feedback!

I guess Dark __Theme__ is better because this repository includes iOS project.

**Comment by kkt-yu** [comment]
Thank you some feedbacks.

**Comment by shinya-takano** [comment]
I Changed to Trial white.
I think white is easy to see.
If there is no problem, i create pull request.

![white_change](https://user-images.githubusercontent.com/2821692/72903110-fc31ae80-3d6f-11ea-9f0c-89f12408b499.png)

**Comment by takahirom** [comment]
Thanks for trying👍
I want to create an app that uses the entire screen, so I don't want to narrow the screen if possible.

**Comment by mukaiyachidaiki** [comment]
What about such a fix?
When using a dark theme on Android9 or lower, set NavigationBar to a color with low transparency.
Sorry, I didn't know how to change the button color.

Android 8 Dark
<img src="https://user-images.githubusercontent.com/726084/73121115-fb8c5880-3fb9-11ea-9e7d-cb293a9fd319.png" width="300px">

Android 8 Light
<img src="https://user-images.githubusercontent.com/726084/73121116-fb8c5880-3fb9-11ea-89d3-85fdb1f69054.png" width="300px">

Android 10 Dark
<img src="https://user-images.githubusercontent.com/726084/73121117-fc24ef00-3fb9-11ea-9190-1a0f13913d1e.png" width="300px">

Android 10 Light
<img src="https://user-images.githubusercontent.com/726084/73121118-fc24ef00-3fb9-11ea-8ebf-8337d856d5df.png" width="300px">

**Comment by takahirom** [comment]
How about  changing navigation bar when    only DarkTheme?👀

**Comment by mukaiyachidaiki** [comment]
@takahirom 
Prepare LiveData in SystemUiManager in a form similar to the status bar, and change the color of the navigation bar according to the OS version when Context.isNightMode changes.

(Referenced code) MainActivity L216
```
statusBarColors.statusBarColor.distinctUntilChanged().observe(this) { color ->
    window.statusBarColor = color
}
```

**Comment by mukaiyachidaiki** [comment]
(英語苦手なので見当違いな回答していたらすみません！)

**Comment by takahirom** [comment]
@mukaiyachidaiki Sorry for late! looks good!

**Comment by mukaiyachidaiki** [comment]
I will try this:raising_hand:

**Comment by FujiKinaga** [comment]
@mukaiyachidaiki 
Assigned!👍
