### ISSUE TITLE
iOS App Hardly see the status bar 

### ISSUE THREAD

**Issue by koogawa** [DroidKaigi/conference-app-2020#499]
## Kind (Required)

- Improvement

 ## Overview (Required)

The colors of the font on the status bar and the status bar background are similar, making it difficult to see.

 
<img src=https://user-images.githubusercontent.com/893643/72772896-a2829480-3c48-11ea-869a-205995b104ff.png  width=50%>

I think it is better to improve like the following.

<img src=https://user-images.githubusercontent.com/893643/72772932-c9d96180-3c48-11ea-8984-746c19127c7a.png  width=50%>

 ## Links	

-

**Comment by koogawa** [comment]
I want to try ✋

**Comment by S-Shimotori** [comment]
I assigned. Thank you.
