### ISSUE TITLE
SearchView keep obtaining focus even if a user close the keyboard with back button

### ISSUE THREAD

**Issue by KeithYokoma** [DroidKaigi/conference-app-2020#500]
**Overview (Required)**
- SearchView keeps obtaining view focus after a back button press so a user cannot close the keyboard, or back to the session list screen with the back button in the system UI or the back gesture.

**Steps To Reproduce**

1. Go to the search screen.
2. SearchView gets focus so that the keyboard comes up.
3. Press the back button to close the keyboard.
4. SearchView immediately gets focus back so that the keyboard comes up again.

**Expected behavior**
Do not obtain focus after closing the keyboard.

**Screenshots**
I will put a recording here later on...

**Env:**
 - Device: Pixel 4 XL
 - OS: Android 10
 - Version: DeployGate #130 / 1.0.5 (1000500)

**Comment by takahirom** [comment]
![back](https://user-images.githubusercontent.com/1386930/72773829-c1cef100-3c4b-11ea-87ca-da8add10ba37.gif)

**Comment by KeithYokoma** [comment]
@takahirom Thanks, that's what I'm talking about...

**Comment by kouhon** [comment]
can i try fix this issue? ✋

**Comment by FujiKinaga** [comment]
@kouhon 
Thanks! Assigned!! 👍
