### ISSUE TITLE
SearchView flickers when click search view delete button if not entered.

### ISSUE THREAD

**Issue by kouhon** [DroidKaigi/conference-app-2020#506]
**Overview (Required)**
- Same as title

**Steps To Reproduce**

1. Go to Search Screen
2. Click on delete button of search view.

**Expected behavior**
Do not searchView flickers.

**Screenshots**
https://github.com/DroidKaigi/conference-app-2020/issues/506#issuecomment-576524470

**Env:**
 - Device: Pixel3xl
 - OS: 10
 - App Version: DeployGate #130

**Comment by kouhon** [comment]
![output](https://user-images.githubusercontent.com/1890628/72777896-7f60e080-3c5a-11ea-9f56-1c4fa36e2f79.gif)

**Comment by KeithYokoma** [comment]
Thanks for reporting the issue!
It looks like this issue is similar to https://github.com/DroidKaigi/conference-app-2020/issues/500, so probably we can resolve #500 and #506 with one resolution 😎

**Comment by KeithYokoma** [comment]
It seems the issue is resolved.
