### ISSUE TITLE
Empty favorite session TextView is cut in half with a large font.

### ISSUE THREAD

**Issue by yamacraft** [DroidKaigi/conference-app-2020#515]
## Kind (Required)

- Improvement

 ## Overview (Required)

- layout_height of TextView is set at a fixed value.
- Text are cut off depending on the font size.

 ## Screenshot	

show layout bounds | font large size
:-: | :-:
![device-2020-01-21-210604](https://user-images.githubusercontent.com/1332886/72805217-aee10e80-3c95-11ea-9088-94d765b89c3f.png) | ![device-2020-01-21-210754](https://user-images.githubusercontent.com/1332886/72805228-b6081c80-3c95-11ea-9d5f-1da68fdadd84.png)

**Comment by yamacraft** [comment]
I'll try to do this issue, ok?

**Comment by takahirom** [comment]
Thank you! Assigned!

**Comment by yamacraft** [comment]
This fix has been fixed in #477.
