### ISSUE TITLE
The front layer of the backdrop (session list) becomes empty and stays in the middle of the screen

### ISSUE THREAD

**Issue by KeithYokoma** [DroidKaigi/conference-app-2020#520]
**Overview (Required)**
- When opening search screen from session list screen
  and come back to session list,
- The front layer of the backdrop (session list) becomes empty
  and it stays in the middle of the screen

I have a screen recording so that you can see what I get in detail.

**Steps To Reproduce**

1. Go to the search screen
2. Click back arrow in the search screen
3. See the backdrop stays in the middle
4. And the session list is invisible

**Expected behavior**
- The backdrop position should be at the bottom (where it was right before opening search screen)
- Session list should be visible

**Screenshots**
![ezgif-6-57037a1fdbee](https://user-images.githubusercontent.com/872595/72808851-c9b78100-3c9d-11ea-8c59-290334a02c81.gif)

**Env:**
 - Device: Pixel 4 XL
 - OS: Android 10
 - Version: DeployGate #139 / 1.0.5 (1000500)

**Additional context**
This is possibly related to https://github.com/DroidKaigi/conference-app-2020/issues/505 as I see the crash and have a crash report having the same stack trace.

**Comment by hirotakaakita** [comment]
I want to try it.

**Comment by e10dokup** [comment]
@hirotakaakita Thanks! assigned 🙋
