### ISSUE TITLE
<a>tag text is not link

### ISSUE THREAD

**Issue by shinya-takano** [DroidKaigi/conference-app-2020#525]
**Overview (Required)**
- <a>tag text is not link

**Expected behavior**
I this <a>tag text is link text

**Screenshots**
![link_lost](https://user-images.githubusercontent.com/2821692/72816111-076ed680-3cab-11ea-9609-86cec82383ca.png)

**Env:**
 - Device: SHV43
 - OS: 9.0
 - App Version or the branch 

**Additional context**
Any other notes

**Comment by shinya-takano** [comment]
if this issue is not bug.i close this issue.

but i think <a> tag should analyze link text

**Comment by takahirom** [comment]
Thanks! I am talking with members🙏

**Comment by takahirom** [comment]
We wanted the URL to be a link, but the tags didn't need to be interpretable. 🙏

**Comment by numa08** [comment]
I'll fix it 🙋‍♂ !

**Comment by FujiKinaga** [comment]
@numa08 
Assigned!👍
