### ISSUE TITLE
iOS Session Cell bottom margin when speaker is empty

### ISSUE THREAD

**Issue by yanamura** [DroidKaigi/conference-app-2020#531]
**Overview (Required)**
- When speaker is empty, SpeakerStackView height is not 0.

**Steps To Reproduce**

1. Go to 'SessionList'
2. See Welcome Talk Cell

**Expected behavior**
Welcome Talk cell's bottom margin become more short

**Screenshots**
![image](https://user-images.githubusercontent.com/875297/72856381-b4723f00-3cfd-11ea-9b3f-5d604433740e.png)

**Env:**
 - iOS

**Additional context**

**Comment by yanamura** [comment]
I will fix it

**Comment by e10dokup** [comment]
@yanamura Good Catch! We assigned this issue to you :bow:
