### ISSUE TITLE
Show session message

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#549]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We don't have a design yet, but we need to give the following message:
![image](https://user-images.githubusercontent.com/1386930/72945448-2ced0480-3dbf-11ea-9972-2a2eb7460ec4.png)
It's okay to just display it once, so I want to add it.

- You can use this message field
https://github.com/droidkaigi/conference-app-2020/blob/master/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Session.kt#L87

 ## Links

**Comment by ochim** [comment]
I want to try it 🙋🏼‍♀️

**Comment by satsukies** [comment]
@ochim Thank you! Assigned!

**Comment by ochim** [comment]
- I can't solve  the conflict
- Where is the image of the mark of the head ?

**Comment by ochim** [comment]
SessionDetailFragment has changed large.
I will change implements.

**Comment by ochim** [comment]
I solved the conflict
