### ISSUE TITLE
Add pin for FloorMapFragment 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#551]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I want to be able to change the pin position depending on the room. (When open from the session)
![image](https://user-images.githubusercontent.com/1386930/72946666-e9949500-3dc2-11ea-83fe-9f2591f1967c.png)

- The map for this room will change later. You do not need to make any adjustments.
![image](https://user-images.githubusercontent.com/1386930/72946511-83a80d80-3dc2-11ea-8711-b410cafe8921.png)

 ## Links	

-

**Comment by Veget-ables** [comment]
Can I try it? 🙋🏼‍♀️

**Comment by KeithYokoma** [comment]
@Veget-ables Thank you and go ahead!

**Comment by Veget-ables** [comment]
@KeithYokoma  I'll try my best 🙏!

**Comment by KeithYokoma** [comment]
@Veget-ables Feel free to ask anything to us here 👍

**Comment by Veget-ables** [comment]
@takahirom @KeithYokoma 
I created PR. Please review it when it’s convenient for you 🙏
best regard.
