### ISSUE TITLE
Add date for first session of day when SessionPage.Favorite

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#552]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/72946924-c28a9300-3dc3-11ea-8866-460f279f01e6.png)

 ## Links	

-

**Comment by PAGMF** [comment]
🙋‍♂

**Comment by CaptainPAG** [comment]
🙋‍♂

**Comment by roana0229** [comment]
Assigned 👍

**Comment by FujiKinaga** [comment]
It seems to be fixed by #574 . So I'll close this PR👋
But, We have a problem in #752.
We are looking forward to someone's contribution!
