### ISSUE TITLE
Sometime session list is not shown

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#553]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It occurs when expand and collapse bottom sheet 🤔 
![second_time_sessions](https://user-images.githubusercontent.com/1386930/72947066-3cbb1780-3dc4-11ea-9900-887b35563665.gif)

 ## Links	

-

**Comment by kuramu1108** [comment]
🙋‍♂️

**Comment by FujiKinaga** [comment]
@kuramu1108 
Thanks again! Assigned!👍
