### ISSUE TITLE
Add Event Tab for sessions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#554]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now that data doesn't exist, but there are events that take place in "Exhibition".
- On this tab, the description appears to be displayed in the screen.
- There is no data for that yet, but the data of the room named Exhibition is included in the data of the list of Sessions.
![image](https://user-images.githubusercontent.com/1386930/72947213-aaffda00-3dc4-11ea-91f6-fde8f5d3d109.png)

 ## Links	

-

**Comment by myoshita** [comment]
I want to try this issue 🙋‍♂

**Comment by takahirom** [comment]
Thanks! Assigned👍
