### ISSUE TITLE
Add license page

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#555]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There are options for this display method, such as using a library, but please choose freely. 😄 

 ## Links	

-

**Comment by rkonno** [comment]
Can I try it? 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
@rkonno If you have any questions. Please tell me 🙏

**Comment by rkonno** [comment]
@takahirom 
Yes, I have a question. Commented on Pull Request. (#687)
Please review them when you have time. I'm grateful for your support.
