### ISSUE TITLE
Remove session survey button

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#556]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We don't use a session survey for this year. So we want to remove that 📝 

![image](https://user-images.githubusercontent.com/1386930/72948376-4cd4f600-3dc8-11ea-9db9-8fbeb51534fc.png)

 ## Links	

-

**Comment by hiroyuki-taguchi** [comment]
I want to try it!

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by a25max** [comment]
Sorry I try it now. @takahirom I can make pull request today.

**Comment by hiroyuki-taguchi** [comment]
@takahirom 
This issue seems to be solved already.
PR #442

Close this issue?

**Comment by takahirom** [comment]
@hiroyuki-taguchi 
Oh.. Sorry. I couldn't manage it 🙇🙇 
I look forward to your contribution.
