### ISSUE TITLE
Adjust the shadow at session list top

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2020#559]
## Kind (Required)
Improvement

 ## Overview (Required)
We found the wrong point for our design of this session list..
There is a feeling of strangeness that there is only a shadow under the divider....

Could you please make the following additional modification however
it goes beyond the scope of the origin issue... 🙇 ?

1. Please change the visibility of divider to invisible if list is scrolled. (#canScrollVertically return true)

2. Please change a width of the shadow view to match recyclers view like so.
<img src="https://user-images.githubusercontent.com/33515193/72959273-34c39d80-3ded-11ea-8e13-0fae1bde9dee.png" width="320px">

 ## Links	
related this PR 
https://github.com/DroidKaigi/conference-app-2020/pull/440

**Comment by yurihondo** [comment]
I am assigned to this issue.

**Comment by rnitame** [comment]
🙋‍♂

**Comment by yurihondo** [comment]
Thanks!!!!
Assigned 🙇
