### ISSUE TITLE
Dark theme chagne when tap Setting in Navigation drawer.

### ISSUE THREAD

**Issue by kouhon** [DroidKaigi/conference-app-2020#560]
**Overview (Required)**
- The dark theme of the app is turned off when tap setting in menu, if device dark theme is set.

**Steps To Reproduce**
Please watch gif attached to screenshots.

**Expected behavior**
Dark theme change when tap dark theme switch.

**Screenshots**
![device-2020-01-23-164504](https://user-images.githubusercontent.com/1890628/72965722-6abe4d00-3e00-11ea-9a4e-1a4d5475083b.gif)

**Env:**
 - Device: Pixel3xl
 - OS: 10
 - deploygate #167

**Comment by takahirom** [comment]
Probably it is fixed in this PR 🙏 Please wait 😄 
https://github.com/DroidKaigi/conference-app-2020/pull/526
