### ISSUE TITLE
Floor map with dark theme

### ISSUE THREAD

**Issue by kumamotone** [DroidKaigi/conference-app-2020#568]
**Overview (Required)**

I think it's hard to see.

<img width="508" alt="スクリーンショット 2020-01-23 23 48 40" src="https://user-images.githubusercontent.com/8403570/72994698-f228b200-3e3a-11ea-95ba-c414cfaddc7a.png">

Sorry that's all.

**Steps To Reproduce**

**Expected behavior**
If it's clear

**Screenshots**
If applicable

**Env:**
 - Device: [e.g. Pixel3]
 - OS: [e.g. 9.0]
 - App Version or the branch [e.g. 0.1.0 or master]

**Additional context**
Any other notes

**Comment by kuramu1108** [comment]
🙋‍♂

**Comment by jmatsu** [comment]
@kuramu1108 
Thank you very much! I'm unsure how this can be resolved so I look forward to your idea. 😃

**Comment by kuramu1108** [comment]
@jmatsu 
I reckon tinting the image should just be fine

**Comment by jmatsu** [comment]
Make sense. 👍
