### ISSUE TITLE
Handle *not found* external integrations like a Calendar app

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2020#571]
## Kind (Required)

- Improvement

 ## Overview (Required)

Not yet merged but https://github.com/DroidKaigi/conference-app-2020/pull/307/files#diff-2b4a7fcb147ae35e0c939da24e583057R33 will throw ActivityNotFoundException if no calendar app has been installed to your device.
We haven't provided a way to handle such a situation, but I believe that it would be great to show a warning and not to exit from an application.

The base strategy is like the following.

- Add new *AppError-inherited class* that represents an error happens on between our app and external integrations e.g. it's *ExtenalIntegrationError* extends *AppError*
- Define new *ExtenalIntegrationError* classes for each integration. For exmaple, it's better to add new *NoCalendarIntegrationFoundException* which extends *ExtenalIntegrationError* for the calendar app integration
- Pass an exception to SystemViewModel#onError at least on Android module

```
fun openCalendar(calendarImplicitIntent: Intent) {
  try {
    activity.startActivity(implicitIntent)
  } catch (e: ActivityNotFoundException) {
    onError(NoCalendarIntegrationFoundException(e))
  }
}
```

Please note that this example may not be compile-able because it's kinda pseudo code.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/pull/307/files#diff-2b4a7fcb147ae35e0c939da24e583057R33

**Comment by k-tomoyasu** [comment]
I will try this :raising_hand:

**Comment by jmatsu** [comment]
@k-tomoyasu 
I assigned this issue to you. Thank you so much. Please feel free to ask us if you have any questions.

The warning message would be like the below.

- `No calendar application was found.` for English
- `カレンダーアプリが見つかりませんでした` for Japanese

**Comment by jmatsu** [comment]
@k-tomoyasu 
For your information, #307 has been merged into *master* branch.

**Comment by k-tomoyasu** [comment]
Thanks for information, sorry for my late reply.  
I will try this weekend!
