### ISSUE TITLE
Support English message for "絞り込み中"

### ISSUE THREAD

**Issue by pps5** [DroidKaigi/conference-app-2020#579]
## Kind (Required)
Improvement

 ## Overview (Required)

"絞り込み中" is always shown regardless of system language setting.
It should be "Filtering" or other message in English.

<img src="https://user-images.githubusercontent.com/12092805/73077746-23b98000-3f04-11ea-8747-5e05296a7208.png" width="50%"/>

## Links
- #516

**Comment by b4tchkn** [comment]
I want to try this!

**Comment by takahirom** [comment]
Thanks! Assigned 👍
