### ISSUE TITLE
Failed ./gradlew :android-base:bundleDebug

### ISSUE THREAD

**Issue by STAR-ZERO** [DroidKaigi/conference-app-2020#591]
**Overview (Required)**
- `./gradlew :android-base:bundleDebug` is getting error.

**Steps To Reproduce**

Run `./gradlew :android-base:bundleDebug`

**Expected behavior**

Build success

**Screenshots**

**Env:**

**Additional context**

```
Execution failed for task ':android-base:packageDebugBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Modules 'base' and 'staff' contain entry 'root/META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory' with different content.
```

**Comment by takahirom** [comment]
I tried to exclude it. But it does not work 😭 

```
    packagingOptions {
        exclude 'META-INF/services/*'
    }
```

**Comment by takahirom** [comment]
base
![image](https://user-images.githubusercontent.com/1386930/73116638-f6f57f00-3f7c-11ea-902a-19fbcc9c207e.png)
staff
![image](https://user-images.githubusercontent.com/1386930/73116647-0c6aa900-3f7d-11ea-9bf9-c05eac7b6b82.png)

**Comment by takahirom** [comment]
![image](https://user-images.githubusercontent.com/1386930/73116657-5eabca00-3f7d-11ea-8d6f-d2a7e5f1536d.png)
