### ISSUE TITLE
Add unit tests for SessionList

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#594]
## Kind (Required)

- Improvement

 ## Overview (Required)

- That class contains many logics!

 ## Links	

-

**Comment by a25max** [comment]
I want to try it

**Comment by takahirom** [comment]
Thanks! Assigned 🙏

**Comment by a25max** [comment]
Sorry, Give up 😢

**Comment by roana0229** [comment]
No problem 😄

**Comment by nashcft** [comment]
This issue is blocked by #614.

**Comment by shiraji** [comment]
It seems no one is working on this one. Can I grab this issue?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
