### ISSUE TITLE
Fix search auto entered

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#596]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  We can not use completion in Android 10
![search_entered](https://user-images.githubusercontent.com/1386930/73117261-05946400-3f86-11ea-91df-7e6b007971e6.gif)

 ## Links	

-

**Comment by sekiya9311** [comment]
Can I try it?

**Comment by takahirom** [comment]
Thanks Assigned!
