### ISSUE TITLE
Which sponsor category title is valid?

### ISSUE THREAD

**Issue by yaslab** [DroidKaigi/conference-app-2020#606]
**Overview (Required)**
- The third sponsor category title differs on where it is used.
    - Android: `SPONSORS` ([definition](https://github.com/DroidKaigi/conference-app-2020/blob/777c57cd8650a7d5c3d0f04274cd4b4ae63fd612/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SponsorCategory.kt#L11))
    - WebSite: `SUPPORTER`

| Android | WebSite |
|:-|:-|
|<img width="212" alt="" src="https://user-images.githubusercontent.com/2077275/73120208-adbe2300-3fae-11ea-9e8b-09b46f222f67.png">|<img width="458" alt="スクリーンショット 2020-01-25 午後8 16 58" src="https://user-images.githubusercontent.com/2077275/73120315-b4996580-3faf-11ea-8764-d77c8c1f1836.png">|

Which title is valid? If `SUPPORTER` is valid, I will fix it with PR #597.

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you. I should fix it 🙏
