### ISSUE TITLE
Automate Dagger Inject

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#608]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Can we use it? 👀 
https://github.com/android/architecture-components-samples/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/di/AppInjector.kt#L31

 ## Links	

-

**Comment by nashcft** [comment]
🙋‍♂

**Comment by satsukies** [comment]
@nashcft Thank you! We assign this issue to you 👍
