### ISSUE TITLE
Fix SessionPage parcelize crash

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#610]
**Overview (Required)**
- 
![image](https://user-images.githubusercontent.com/1386930/73120951-f6c6a500-3fb7-11ea-8c14-006f6fe0a0cd.png)

**Steps To Reproduce**
1. Check Don't keep Activity in developers options
2. Show sessions
3. Press home button, Go to launcher app
4. relaunch

**Expected behavior**
Not crash

**Env:**
 - Device: Pixel3
 - OS: 10.0
 - master

**Comment by takahirom** [comment]
I think we can fix it by adding AndroidParcelize for subclasses.
https://github.com/DroidKaigi/conference-app-2020/blob/master/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionPage.kt

**Comment by myoshita** [comment]
Can I fix it ?

**Comment by takahirom** [comment]
Please do it! 🙏
