### ISSUE TITLE
This tag and its children can be replaced by one <TextView/> and a compound drawable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#611]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The lint say it.
- Can we do it?? 👀 
https://github.com/DroidKaigi/conference-app-2020/blob/ba799e8c11633a0d9e6d9b400961d0582cb0358e/feature/session/src/main/res/layout/item_session_detail_speaker.xml#L19

 ## Links	

-

**Comment by hoyo** [comment]
I will try this. 🙋‍♂

**Comment by takahirom** [comment]
Thanks! Assigned
