### ISSUE TITLE
Problem with clicking the view

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2020#625]
**Overview (Required)**
- Touching BottomSheet on the main screen activates the Filter under BottomSheet.

**Steps To Reproduce**

1. Run DroidKaigi 2020
2. Click on 'Click in some area of BottomSheet'
3. The filter becomes valid

**Expected behavior**
The filter should not be valid.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1534926/73136067-bd139e00-408c-11ea-887f-f24694e940a2.gif" width="300" />

**Env:**
 - Device: Pixel3a
 - OS: 10
 - 1.0.5

**Additional context**
My expectation is that the filter should not be valid.
But I need advice from Organizer.

**Comment by ytRino** [comment]
ah #630 is.

**Comment by hiroyuki-taguchi** [comment]
Sorry, I didn't notice this issue.
I want to try!
