### ISSUE TITLE
the session list scrolls to the top, when click favorite button.

### ISSUE THREAD

**Issue by kouhon** [DroidKaigi/conference-app-2020#629]
**Overview (Required)**
- same as title.

**Steps To Reproduce**

1. Scroll session list.
2. Click on favorite.

**Expected behavior**
do not scrolls when click favorite.

**Screenshots**
If applicable

**Env:**
 - Device: Pixel3XL
 - OS: 10
 - deploygate #209

**Additional context**
Any other notes

**Comment by mhidaka** [comment]
Thank you for your report!

**Comment by undoroid** [comment]
I will try this 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 🙏

**Comment by takahirom** [comment]
@undoroid Sorry. Other pull request fixs this issue🙇
I look forward to your next contribution🙏
