### ISSUE TITLE
Use ContentLoadingProgressBar instead of ProgressBar with ProgressTimeLatch

### ISSUE THREAD

**Issue by rmakiyama** [DroidKaigi/conference-app-2020#642]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- ContentLoadingProgressBar is useful view.
- ContentLoadingProgressBar might be able to do the same as ProgressBar with ProgressTimeLatch
- Or, we dare to use ProgressBar because of some reason?

 ## Links	

- [ContentLoadingProgressBar](https://developer.android.google.cn/reference/kotlin/androidx/core/widget/ContentLoadingProgressBar)
- [ProgressTimeLatchとは何なのか](https://qiita.com/tsumuchan/items/38346528da5ebb8d8e64)

**Comment by rmakiyama** [comment]
if you like, I will try it 🙋‍♂

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I knew that View, but I didn't use it. However, considering the current situation, ContentLoadingProgressBar may be more appropriate because only ProgressBar is used.
Please do it 🙏
