### ISSUE TITLE
Add the entire survey to the navigation drawer

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#652]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We want to add entire survey("全体アンケート") navigation drawer item to Navigation Drawer
- Since the URL has not yet been determined, please access google.com when you press the button. 🙏 

 ## Links	

-

**Comment by Takafumi-Orita** [comment]
What do you do with the icons?

**Comment by tkt989** [comment]
I want to try it !

**Comment by takahirom** [comment]
Thanks! Assigned 🙏

**Comment by tkt989** [comment]
What icon should I use for entire survey?

**Comment by takahirom** [comment]
How about a feedback icon? 👀 
https://material.io/resources/icons/?icon=feedback&style=round

**Comment by tkt989** [comment]
I got it.
Thanks!
