### ISSUE TITLE
Update Dagger

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#655]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now Dagger uses AndroidX!

 ## Links	

-

**Comment by RyuNen344** [comment]
✋

**Comment by satsukies** [comment]
@RyuNen344 Thank you! We assign this issue to you 👍

**Comment by satsukies** [comment]
@RyuNen344 
This issue has PR already created and I was overlooking.
So sorry.

We look forward to your contribution to another issue!

**Comment by RyuNen344** [comment]
😢 
never mind
