### ISSUE TITLE
iOS Add "Event" to tab

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#657]
## Kind (Required)
- Improvement

 ## Overview (Required)
- add "Event" tab to FilterViewController.

 ## Links	
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=1279%3A1339

**Comment by clockvoid** [comment]
Yesterday, I tried it and I did it.

Like this ->
<img width="300" src="https://user-images.githubusercontent.com/6965122/73599748-3a0dae80-458a-11ea-8928-574d57fbb155.png" />

However, I'm so nervous because I'm a beginner to develop iOS apps.
Do you face me if I submit a PR?

**Comment by ry-itto** [comment]
@clockvoid 
Thanks 😄 
It is ok to implement adding tab only. 👍
If you create a PR, we will check it.

**Comment by clockvoid** [comment]
@ry-itto 
I created a new PR #708 to fix an issue due to my misunderstanding. Please check it.
I'm sorry to compound the problem. 🙇
