### ISSUE TITLE
iOS Make rounded corner to SessionView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#661]
## Kind (Required)

Choose the suitable template if exists.
- Improvement

 ## Overview (Required)
- Now, `SessionView`'s left corner is not rounded. So please make rounded.

### Current
<img src="https://user-images.githubusercontent.com/30540303/73423888-c5abf300-4370-11ea-9367-339ed4858ef9.png" width="200px">

 ## Links
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=4%3A2

**Comment by fummicc1** [comment]
If nobody tries this challenge, I would like to try 👀

**Comment by ry-itto** [comment]
@fummicc1 
Thanks! 
Assigned 👍
