### ISSUE TITLE
Exclude event sessions from day sessions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#669]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There are currently no event sessions, but if added, they will be displayed in the dated session list and event tab. I want to exclude it from day sessions🙏 

 ## Links	

-

**Comment by tick-taku** [comment]
Hi! 🙋
Can I try this ?

**Comment by roana0229** [comment]
Of course 👍 
Assigned.
