### ISSUE TITLE
Add about screen description for english

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#679]
## Kind (Required)

- Improvement
- Other

 ## Overview (Required)
From https://droidkaigi.jp/2020/en/
DroidKaigi is a conference tailored for Android developers. It's scheduled to take place on the 20 and 21 of February 2020.
- https://github.com/DroidKaigi/conference-app-2020/blob/7f29bcb303e6056a933b9d687b21c9804640f647/feature/about/src/main/res/values/strings.xml#L4

 ## Links	

-

**Comment by torikatsupg** [comment]
Can I try this issue ?

**Comment by takahirom** [comment]
Thanks! Assinged 👍
