### ISSUE TITLE
Add `Access` implementation in about screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#680]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- I'm thinking about launching Google Map with an implicit intent.
-  https://github.com/DroidKaigi/conference-app-2020/blob/7f29bcb303e6056a933b9d687b21c9804640f647/feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt#L89

 ## Links	

-

**Comment by youmitsu** [comment]
🙋‍♂️

**Comment by roana0229** [comment]
Assigned 👍
