### ISSUE TITLE
Go to privacy policy page from About DroidKaigi screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#681]
## Kind (Required)

- Proposal / Discussion

## Overview (Required)
- We want to go just this page.
- http://www.association.droidkaigi.jp/privacy.html
https://github.com/DroidKaigi/conference-app-2020/blob/7f29bcb303e6056a933b9d687b21c9804640f647/feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt#L99

 ## Links	

-

**Comment by kuramu1108** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
