### ISSUE TITLE
Text color in About page does not consider dark mode

### ISSUE THREAD

**Issue by nashcft** [DroidKaigi/conference-app-2020#686]
**Overview (Required)**

`textColor` for the texts in About page refers directly to color resources, so their color does not change according to the change of  the app's theme.

**Steps To Reproduce**

1. Go to 'Settings'
1. Set theme to 'Dark'
1. Go to 'About'

**Expected behavior**

Text color should be changed corresponding to selected color theme; i.e. use theme's color attribute for the value of `textColor`.

**Screenshots**

| Light | Dark |
| -- | -- |
| ![light](https://user-images.githubusercontent.com/7891554/73589702-355ee100-451d-11ea-9d35-d50948cb2da4.png) | ![dark](https://user-images.githubusercontent.com/7891554/73589704-414aa300-451d-11ea-985c-387efdc7bc7c.png) |

**Env:**

 - Device: Pixel3
 - OS: 10
 - App Version or the branch [e.g. 0.1.0 or master]: master

**Comment by takahirom** [comment]
Thanks for reporting!

**Comment by clockvoid** [comment]
I could fix it.
The color of version number text was not destined, so I use white in dark mode.
May I make PR with this result?

| Light | Dark |
| ----- | ----- |
| <img src="https://user-images.githubusercontent.com/6965122/73596137-feabb980-4562-11ea-9213-f6872fe57d0c.png" width="250" /> | <img src="https://user-images.githubusercontent.com/6965122/73596136-feabb980-4562-11ea-944c-f8638566dc40.png" width="250" /> |

**Comment by takahirom** [comment]
@clockvoid 🙆
