### ISSUE TITLE
Fix SessionsViewModelTest fail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#697]
## Kind (Required)

- Improvement

 ## Overview (Required)

- SessionsViewModelTest test is broken 😭 
![image](https://user-images.githubusercontent.com/1386930/73605826-77078e80-45e6-11ea-8a4d-c5bf578cbc48.png)

 ## Links	

-

**Comment by sekiya9311** [comment]
Can I fix it?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
