### ISSUE TITLE
[iOS] Show "LIVE" tag only in living.

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#704]
## Kind (Required)
- Improvement

 ## Overview (Required)
- In SessionView, there are "LIVE" tag for all cells now. It should show in living only.
- Please show "LIVE" tag only in living.

"LIVE" tag represents following.
<img width="43" alt="スクリーンショット 2020-02-02 22 43 32" src="https://user-images.githubusercontent.com/30540303/73609098-a2ea3a80-460d-11ea-969d-7a45435c26b4.png">

 ## Links	

-

**Comment by KaoruMuta** [comment]
I'd like to try this issue if possible!

**Comment by roana0229** [comment]
Of course, assigned 👍
