### ISSUE TITLE
Level filter does not work correctly?

### ISSUE THREAD

**Issue by clockvoid** [DroidKaigi/conference-app-2020#709]
**Overview (Required)**
I think FiltersTest does not pass correctly.
Because the data class Session has no member "forBeginners" but the test checks this parameter.
Additionally, data class has the member "intendedAudience", but the actual response doesn't have that.
SessionEntity's intendedAudience value is [always null](https://github.com/DroidKaigi/conference-app-2020/blob/master/data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/entity/mapper/SessionDataMapperExt.kt#L95).
And also, the Filters#isPass() method [does not check audience categories](https://github.com/DroidKaigi/conference-app-2020/blob/master/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Filters.kt#L10).
I think this app's audience filter function is not working.
Both in day1 and day2, the results are the same with or without the level filters.

**Steps To Reproduce**

1. Go to top
2. Click on level filters
4. See Applicable session number

**Expected behavior**
Filter sessions by audience categories.

**Screenshots**

| | beginners | both level |
| ----- | ----- | ----- |
| day1 | <img src="https://user-images.githubusercontent.com/6965122/73687863-3c991100-470e-11ea-94db-4702addb6e97.png" width="300" /> | <img src="https://user-images.githubusercontent.com/6965122/73687865-3c991100-470e-11ea-915d-9028f60289e4.png" width="300" /> |
| day2 | <img src="https://user-images.githubusercontent.com/6965122/73687866-3d31a780-470e-11ea-995d-abbd61d7e140.png" width="300" /> | <img src="https://user-images.githubusercontent.com/6965122/73687867-3d31a780-470e-11ea-9993-aee82d3d04f3.png" width="300" /> |

**Env:**
 - Device: Pixel 4
 - OS: 10
 - App Version or the branch: 1.2.0 on c4661b203be2bddac1a006659d88335efafc1c15 (latest master branch)

**Additional context**
I found this problem when researching #614 . But this issue is more deep-seated than I thought, so I divided.

**Comment by takahirom** [comment]
Probably we should implement audience level🙏

**Comment by clockvoid** [comment]
@takahirom 
Thank you for your replying.
I want to implement it.
I will implement it like 2019 version app to pass the FiltersTest.

**Comment by takahirom** [comment]
Thanks! Assigned!🙏

**Comment by takahirom** [comment]
I think we should have list. Not forBeginer field. 
forBeginnerのようなフィールドではなく、レベルをリストで持ってるような構造にする必要がありそうです🙏

**Comment by clockvoid** [comment]
I see.
すみません、日本語で失礼します。
レスポンスを見るとリストで持っていますね...
3つ要素があるようですが、アプリのフィルターは2つしか持ってないです。これ3つめは何なんですかね...？

**Comment by takahirom** [comment]
初心者向け、中級者、上級者だった気がします🙏

**Comment by clockvoid** [comment]
理解です。
多分これアプリ側のフィルターとしても全部必要かと思いますので、そこも含めてやっちゃいます

**Comment by takahirom** [comment]
あってます。ありがとうございます😂
