### ISSUE TITLE
A privacy policy toolbar color does not adapt to dark mode

### ISSUE THREAD

**Issue by koji-1009** [DroidKaigi/conference-app-2020#716]
## Kind (Required)

- Improvement

 ## Overview (Required)

- A toolbar color of Privacy Policy is not adapt dark mode

page | light | dark
:---: | :---: | :---:
about | ![light_about](https://user-images.githubusercontent.com/17231507/73801178-f4a4e780-47fc-11ea-8f9a-337cbdfe0d3c.png) | ![dark_about](https://user-images.githubusercontent.com/17231507/73801173-f2428d80-47fc-11ea-8c61-e8d6216f9011.png)
privacy policy | ![light_pp](https://user-images.githubusercontent.com/17231507/73801183-f79fd800-47fc-11ea-9ff0-fb4b7edbf1dc.png) | ![dark_pp](https://user-images.githubusercontent.com/17231507/73801181-f7074180-47fc-11ea-89c4-fac460bd7eaf.png)

 ## Links	

- <https://material.io/design/color/dark-theme.html#ui-application>

**Comment by kikulinx** [comment]
:raising_hand:

**Comment by roana0229** [comment]
Assigned 👍
