### ISSUE TITLE
Use server side image for floor map(Android)

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#717]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably, we can not prepare image early. So  we should use server-side image
https://api.droidkaigi.jp/images/2020/map.png

 ## Links	

-

**Comment by kuramu1108** [comment]
🙋‍♂️

**Comment by yurihondo** [comment]
Assigned Thanks 🙏
