### ISSUE TITLE
Crash when click share button in welcome talk detail

### ISSUE THREAD

**Issue by alto-tone** [DroidKaigi/conference-app-2020#719]
**Overview (Required)**
- Crash when click share button in welcome talk detail

**Steps To Reproduce**

1. Go to Welcome Talk detail
2. Click on share button
3. See error

**Screenshots**
<img src="https://user-images.githubusercontent.com/9940385/73842996-11730680-4861-11ea-9507-c246cedaafa1.png" width="300">

**Env:**
 - Device: Pixel3 XL
 - OS: 9.0
 - the branch: master

**Comment by alto-tone** [comment]
I want to challenge 🙋‍♀️

**Comment by takahirom** [comment]
Thank you for reporting!! Assigned🙏

**Comment by alto-tone** [comment]
@takahirom 
There are three ways. Which one is better?

1. Create url
    - e.g. https://droidkaigi.jp/2020/en/timetable/274c1d32-b975-4b9c-8423-13d9175f6d2a
2. Hide share button
3. Make unable to open detail
    - DroidKaigi 2019 can not open welcome talk detail. but party detail can open. 

Lunch and Party also crash.
I fix together.

**Comment by takahirom** [comment]
Thanks! Let me think!🙏

**Comment by takahirom** [comment]
I talked web engineer. Please do No. 1 !🙏

**Comment by alto-tone** [comment]
OK, thank you for thinking!
