### ISSUE TITLE
Add white text logo for drawer

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#725]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably we should add an image for it 👀 
![image](https://user-images.githubusercontent.com/1386930/73901869-5afe3880-48d7-11ea-9a4b-63bad67c02d0.png)

 ## Links	

-

**Comment by takahirom** [comment]
https://github.com/DroidKaigi/conference-app-2020/blob/master/android-base/src/main/res/drawable-xhdpi/logo.webp

**Comment by takahirom** [comment]
Downloading the figma file and modifying it may be possible.

**Comment by JajaDoc** [comment]
🙋

**Comment by roana0229** [comment]
Assigned 👍
