### ISSUE TITLE
[iOS] Add License Info

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2020#745]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
- Title is all.
- By using `LicensePlist`, please add license info to this app.
- Make transition from `About DroidKaigi` view to Setting App and show License.

 ## Links	
- [LicensePlist](https://github.com/mono0926/LicensePlist)
- [[iOS11][swift] アプリから自分の設定ページを開く方法](https://gekkado.com/archives/590)

**Comment by takahirom** [comment]
I think adding a license list is good. However, this is not required because this Application is open source. 👍

**Comment by ry-itto** [comment]
Exactly! I see. 👍

**Comment by uhooi** [comment]
🙋

**Comment by ry-itto** [comment]
Thanks! 
Assigned 👍
