### ISSUE TITLE
[iOS] Probably not passed CONFIGURATION to Gradle

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#747]
## Kind (Required)

- Improvement

 ## Overview (Required)

- So the API URL is not changed.
-  https://github.com/droidkaigi/conference-app-2020/blob/master/ios-base/scripts/build_kotlin_modules.sh#L5

 ## Links	

-

**Comment by takahirom** [comment]
We want to use it here
https://github.com/droidkaigi/conference-app-2020/blob/master/ios-combined/build.gradle#L70

**Comment by ry-itto** [comment]
I think the property is passed to Gradle.
I tried it to put a code `println mode` to next line of `ios-combined/build.gradle` L70.
Like this.
```
final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'
println mode
```
And This is executing result.
```shell
> BUILD_IOS=true ./gradlew ios-combined:linkIosX64 -PXCODE_CONFIGURATION=Release
```
```
> Configure project :android-base
WARNING:
....
> Configure project :ios-combined
Kotlin Multiplatform Projects are an experimental feature.
RELEASE
<-------------> 0% EXECUTING [7s]
```

The way of confirming above is correct, I think it passed.

I think this option is probably passing property to gradle. `-PXCODE_CONFIGURATION=${CONFIGURATION}` 
And in Xcode, `CONFIGURATION` property represents a build mode such as `Debug` or `Release`.

**Comment by takahirom** [comment]
Thanks! I can not switch develop API and production API. Can you do it? production api has event sessions!

**Comment by takahirom** [comment]
When I confirm event session. I rewrite url😂

**Comment by ry-itto** [comment]
I see! I will try it 😄

**Comment by ry-itto** [comment]
I'm sorry I can't confirm showing event sessions...
Can I tell how to show that? 🙏 

I tried following in `scripts/build_kotlin_modules.sh`
```
 BUILD_IOS=true ./gradlew :ios-combined:$KN_LIBRARY_BUILD_TASK -PXCODE_CONFIGURATION=Production
```

**Comment by takahirom** [comment]
I changed this API endpoint to `http://api.droidkaigi.jp/2020`
https://github.com/droidkaigi/conference-app-2020/blob/master/data/api/src/iosMain/kotlinDebug/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt#L4
FYR you can check timetable
http://deploy-preview-49--droidkaigi-api-dev.netlify.com/2020/timetable
https://api.droidkaigi.jp/2020/timetable/

**Comment by takahirom** [comment]
Probably you should use RELEASE instead of Production
https://github.com/droidkaigi/conference-app-2020/blob/master/ios-combined/build.gradle#L73

**Comment by takahirom** [comment]
Probably you should use RELEASE instead of Production
https://github.com/droidkaigi/conference-app-2020/blob/master/ios-combined/build.gradle#L73

**Comment by ry-itto** [comment]
I understand. I will try with `Release`. 👍

**Comment by ry-itto** [comment]
Thanks! I confirmed 🙏 
I may miss some point...

**Comment by ry-itto** [comment]
Please try this with https://github.com/DroidKaigi/conference-app-2020/pull/753 ? 🙏
