### ISSUE TITLE
[iOS]Session message

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#748]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  I want to display a message used when the location of the session changes. There is data to be displayed in session.message.ja etc.
![image](https://user-images.githubusercontent.com/1386930/74133419-e1927d00-4c2b-11ea-8802-30826976ed27.png)

 ## Links	

-

**Comment by usayuki** [comment]
🙋

**Comment by roana0229** [comment]
Assigned 👍

**Comment by usayuki** [comment]
@takahirom 
Where is this design on figma?
I could not find it in this file
https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App

**Comment by takahirom** [comment]
Unfortunately, there is no such design.  😂

**Comment by takahirom** [comment]
It is important to be able to display anyway.🙇
