### ISSUE TITLE
Expand animation is incorrect when tap "Read more" button in session detail

### ISSUE THREAD

**Issue by koji-1009** [DroidKaigi/conference-app-2020#751]
**Overview (Required)**

- Tap "Read more" button, the speaker cell is overlapped the description cell.
- Then, scroll down speaker cell and show the description cell.

**Steps To Reproduce**

1. Go to SessionDetail
2. Click on "Read more" button
3. See animation

**Expected behavior**

Cells do not overlap.

**Screenshots**

<img src="https://user-images.githubusercontent.com/17231507/74101528-219b2680-4b7e-11ea-896a-e9f5e6b963ed.gif" width="300">

**Env:**
 - Device: Pixel 2(emulator)
 - OS: 10
 - master

**Additional context**

Maybe this is a degraded problem.
See DeployGate at #592 and #682 .

**Comment by devKeeey** [comment]
This issue can be avoided by running "adapter.clear()" before "adapter.update(items)" in the setupSessionViews method of the SessionDetailFragment class, but I'm not sure this implementation is correct.

When "adapter.clear ()" is run, "notifyItemRangeInserted()" works.
When "adapter.clear ()" is not run, "notifyItemRangeChanged()" works.

```Kotlin
// Example: SessionDetailFragment class line 247

adapter.clear()
adapter.update(items)
startPostponedEnterTransition()
```


![01](https://user-images.githubusercontent.com/60731158/74143880-fc222180-4c3e-11ea-91d1-03179560cde5.gif)
