### ISSUE TITLE
[iOS] Apply event item text design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#756]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/74106185-c4b46600-4ba7-11ea-92f1-7c2d608cb708.png)

 ## Links	

-

**Comment by isaoeka** [comment]
🙋‍♂️

**Comment by ry-itto** [comment]
Thanks! Assigned 👍
