### ISSUE TITLE
[iOS]Stop use UIWebView APIs

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#760]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

-Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

 ## Links	

-

**Comment by ry-itto** [comment]
I think our iOS app don't use `UIWebView` 🤔 
Are there place you found?

**Comment by takahirom** [comment]
Rx..? 🤔 
![image](https://user-images.githubusercontent.com/1386930/74219960-993d9280-4cf1-11ea-9b6a-1834502c4cef.png)

**Comment by ry-itto** [comment]
I see. It's defined in `RxCocoa` as extension...
Do these extensions make some problems?

**Comment by takahirom** [comment]
If you use it, it seems that you can not release it in April, but I think it is not related to the release of this app, so I do not need to do anything. 😄

**Comment by ry-itto** [comment]
I understand. 👍

**Comment by ry-itto** [comment]
This is related to https://github.com/ReactiveX/RxSwift/issues/2055.
And in above issue, there will release that doesn't have `UIWebView` extention.
We should wait for `RxSwift` 's release, but it can't by no time remaining....
So we will continue without resolving this. 😄
