### ISSUE TITLE
[iOS] Crash on app launch

### ISSUE THREAD

**Issue by uhooi** [DroidKaigi/conference-app-2020#766]
**Overview (Required)**
- Crash on app launch by "dyld: Library not loaded".

**Steps To Reproduce**

1. Run in simulator.
2. See error
```
dyld: Library not loaded: @rpath/ios_combined.framework/ios_combined
  Referenced from: /Users/{user name}/Library/Developer/CoreSimulator/Devices/DF9B6B85-3D21-46A3-9DED-2737E0D191A0/data/Containers/Bundle/Application/61B9CFF3-C675-4AE0-99FE-EF6A9DAC78A2/DroidKaigi 2020.app/DroidKaigi 2020
  Reason: image not found
```

**Env:**
- Xcode: 11.3.1

**Similar (same?) issues:**
- #738

**Comment by uhooi** [comment]
I've tried again with complete clean the `Derived Data` directory.
But it could not to resolve.

**Comment by ry-itto** [comment]
please try this https://github.com/DroidKaigi/conference-app-2020/pull/765 🙏 

and rm ios-based/build directory 🙏

**Comment by uhooi** [comment]
thx!!
And replaced all `ios_combined` with `ioscombined` .
Build succeeded💪

**Comment by roana0229** [comment]
👍 
Thank you for report 😄
