### ISSUE TITLE
[iOS]Add entire survey

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#783]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add a navigation drawer item

![image](https://user-images.githubusercontent.com/1386930/74584323-74f4f500-5014-11ea-8388-1d1e04d45b25.png)

 ## Links	

- survey link https://docs.google.com/forms/d/1pm-47edcdP3BYp59_cImgrvXiEOWYTxtXYUUb8CpeE8/viewform

**Comment by ry-itto** [comment]
I will do this 👍

**Comment by takahirom** [comment]
🙏
