### ISSUE TITLE
Use https connection

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2020#785]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably we can use https connection and remove clear text (Manifest.xml) by adding URL last `/`

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/master/data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/KtorDroidKaigiApi.kt#L40
 - https://github.com/DroidKaigi/conference-app-2020/blob/master/android-base/src/main/AndroidManifest.xml#L11

**Comment by emusute1212** [comment]
I want try this 🙋‍♂ 

This is `welcome contribute` ??

**Comment by takahirom** [comment]
Yes! Thanks!
