### ISSUE TITLE
Add Google play Link at Readme file

### ISSUE THREAD

**Issue by mhidaka** [DroidKaigi/conference-app-2020#794]
## Kind (Required)

- Improvement

 ## Overview (Required)
Add Google play Link at Readme 

![image](https://user-images.githubusercontent.com/322019/74592370-ef993100-5063-11ea-87e4-308e2c8efd01.png)

```
You can install the production app via Get it on Google Play. // TODO: Add link to Google Play
```

 ## Links	

https://play.google.com/store/apps/details?id=io.github.droidkaigi.confsched2020

**Comment by nakasho-dev** [comment]
🙋‍♂

**Comment by takahirom** [comment]
Thanks! Assigned 👍
