### ISSUE TITLE
Update Android Gradle Plugin 3.6 RC3

### ISSUE THREAD

**Issue by koji-1009** [DroidKaigi/conference-app-2020#801]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Android Studio 3.6 RC3 was released on February 10

 ## Links	

- <https://androidstudio.googleblog.com/2020/02/android-studio-36-release-candidate-3.html>

**Comment by yoshida0261** [comment]
🙋‍♂️

**Comment by satsukies** [comment]
@yoshida0261 
Thanks! Assigned 👍
