### ISSUE TITLE
WTF !!  lost  library  &  di error !!

### ISSUE THREAD

**Issue by CMingTseng** [DroidKaigi/conference-app-2020#828]
Dear Sir
 
very thanks the codelab-2020 

https://droidkaigi.github.io/codelab-2020/en/index.html#0

but the demo code  https://github.com/DroidKaigi/architecture-components-samples.git

(branch :  droidkaigi-2020-codelab  &  droidkaigi-2020-codelab-modularized )

lost something !!

@ versions.gradle 

1.  lifecycle.runtime_ktx   --> app & feature:login 

2.  kotpref_initializer &  kotpref_core  --> data:repository

3.  deps.browser  --> feature:login 

can not di !!! 

LoginActivity @feature:login get error 

it show  

Can not access  'android.lifecycle.HasDefaultViewModelProviderFactory' which is supertype of 'com.android.example.feature.login.LoginActivity'.Check your module classpath for missing or conflicting dependencies

THX

**Comment by takahirom** [comment]
Thank you for reporting! I'll contact the creator of codelab-2020.

**Comment by tomoya0x00** [comment]
👀

**Comment by tomoya0x00** [comment]
@CMingTseng Hi!

Can you check that you opened the GithubBrowserSample project?

![スクリーンショット 2021-01-06 1 12 33](https://user-images.githubusercontent.com/5106629/103669963-572dd700-4fbc-11eb-9abb-0cc24c1763c0.png)

On my Mac, both branches were built successfully with Android Studio 4.1.1.

Thanks!

**Comment by CMingTseng** [comment]
> @CMingTseng Hi!
> 
> Can you check that you opened the GithubBrowserSample project?
> 
> ![スクリーンショット 2021-01-06 1 12 33](https://user-images.githubusercontent.com/5106629/103669963-572dd700-4fbc-11eb-9abb-0cc24c1763c0.png)
> 
> On my Mac, both branches were built successfully with Android Studio 4.1.1.
> 
> Thanks!

Dear Sir  

THX

now  i know why !!

the demo project  has  over two versions.gradle 

first  i clone it  , and then modify structure project  (like add setting.gradle at  rootpath  ...balabala )

the outside versions.gradle is different versions.gradle at GithubBrowserSample (something is different )

so l lost dependencies library 

but   some sub_project can not standalone build as library  aar file 

THX
